<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Inference | Data Analysis for the Life Sciences with R: Exercise Solutions (in progress)</title>
  <meta name="description" content="Chapter 3 Inference | Data Analysis for the Life Sciences with R: Exercise Solutions (in progress)" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Inference | Data Analysis for the Life Sciences with R: Exercise Solutions (in progress)" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Inference | Data Analysis for the Life Sciences with R: Exercise Solutions (in progress)" />
  
  
  

<meta name="author" content="Seung Hyun (Sam) Min" />


<meta name="date" content="2020-12-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="getting-started.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">DA4LS with R: Exercise Solutions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgment"><i class="fa fa-check"></i>Acknowledgment</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#frequently-asked-questions"><i class="fa fa-check"></i>Frequently Asked Questions</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>1</b> Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#ch-3.8-exercises"><i class="fa fa-check"></i><b>1.1</b> Ch 3.8 Exercises</a><ul>
<li class="chapter" data-level="1.1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#question-1"><i class="fa fa-check"></i><b>1.1.1</b> Question 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>2</b> Getting started</a></li>
<li class="chapter" data-level="3" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>3</b> Inference</a><ul>
<li class="chapter" data-level="3.1" data-path="inference.html"><a href="inference.html#ch-2.7-exercises"><i class="fa fa-check"></i><b>3.1</b> Ch 2.7 Exercises</a><ul>
<li class="chapter" data-level="3.1.1" data-path="inference.html"><a href="inference.html#question-1-1"><i class="fa fa-check"></i><b>3.1.1</b> Question 1</a></li>
<li class="chapter" data-level="3.1.2" data-path="inference.html"><a href="inference.html#question-2"><i class="fa fa-check"></i><b>3.1.2</b> Question 2</a></li>
<li class="chapter" data-level="3.1.3" data-path="inference.html"><a href="inference.html#question-3"><i class="fa fa-check"></i><b>3.1.3</b> Question 3</a></li>
<li class="chapter" data-level="3.1.4" data-path="inference.html"><a href="inference.html#question-4"><i class="fa fa-check"></i><b>3.1.4</b> Question 4</a></li>
<li class="chapter" data-level="3.1.5" data-path="inference.html"><a href="inference.html#question-5"><i class="fa fa-check"></i><b>3.1.5</b> Question 5</a></li>
<li class="chapter" data-level="3.1.6" data-path="inference.html"><a href="inference.html#question-6"><i class="fa fa-check"></i><b>3.1.6</b> Question 6</a></li>
<li class="chapter" data-level="3.1.7" data-path="inference.html"><a href="inference.html#question-7"><i class="fa fa-check"></i><b>3.1.7</b> Question 7</a></li>
<li class="chapter" data-level="3.1.8" data-path="inference.html"><a href="inference.html#question-8"><i class="fa fa-check"></i><b>3.1.8</b> Question 8</a></li>
<li class="chapter" data-level="3.1.9" data-path="inference.html"><a href="inference.html#question-9"><i class="fa fa-check"></i><b>3.1.9</b> Question 9</a></li>
<li class="chapter" data-level="3.1.10" data-path="inference.html"><a href="inference.html#question-10"><i class="fa fa-check"></i><b>3.1.10</b> Question 10</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="inference.html"><a href="inference.html#ch-2.9-exercises"><i class="fa fa-check"></i><b>3.2</b> Ch 2.9 Exercises</a><ul>
<li class="chapter" data-level="3.2.1" data-path="inference.html"><a href="inference.html#question-1-2"><i class="fa fa-check"></i><b>3.2.1</b> Question 1</a></li>
<li class="chapter" data-level="3.2.2" data-path="inference.html"><a href="inference.html#question-2-1"><i class="fa fa-check"></i><b>3.2.2</b> Question 2</a></li>
<li class="chapter" data-level="3.2.3" data-path="inference.html"><a href="inference.html#question-3-1"><i class="fa fa-check"></i><b>3.2.3</b> Question 3</a></li>
<li class="chapter" data-level="3.2.4" data-path="inference.html"><a href="inference.html#question-4-1"><i class="fa fa-check"></i><b>3.2.4</b> Question 4</a></li>
<li class="chapter" data-level="3.2.5" data-path="inference.html"><a href="inference.html#question-5-1"><i class="fa fa-check"></i><b>3.2.5</b> Question 5</a></li>
<li class="chapter" data-level="3.2.6" data-path="inference.html"><a href="inference.html#question-6-1"><i class="fa fa-check"></i><b>3.2.6</b> Question 6</a></li>
<li class="chapter" data-level="3.2.7" data-path="inference.html"><a href="inference.html#question-7-1"><i class="fa fa-check"></i><b>3.2.7</b> Question 7</a></li>
<li class="chapter" data-level="3.2.8" data-path="inference.html"><a href="inference.html#question-8-1"><i class="fa fa-check"></i><b>3.2.8</b> Question 8</a></li>
<li class="chapter" data-level="3.2.9" data-path="inference.html"><a href="inference.html#question-9-1"><i class="fa fa-check"></i><b>3.2.9</b> Question 9</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="inference.html"><a href="inference.html#ch-2.11-exercises"><i class="fa fa-check"></i><b>3.3</b> Ch 2.11 Exercises</a><ul>
<li class="chapter" data-level="3.3.1" data-path="inference.html"><a href="inference.html#question-1-3"><i class="fa fa-check"></i><b>3.3.1</b> Question 1</a></li>
<li class="chapter" data-level="3.3.2" data-path="inference.html"><a href="inference.html#question-2-2"><i class="fa fa-check"></i><b>3.3.2</b> Question 2</a></li>
<li class="chapter" data-level="3.3.3" data-path="inference.html"><a href="inference.html#question-3-2"><i class="fa fa-check"></i><b>3.3.3</b> Question 3</a></li>
<li class="chapter" data-level="3.3.4" data-path="inference.html"><a href="inference.html#question-4-2"><i class="fa fa-check"></i><b>3.3.4</b> Question 4</a></li>
<li class="chapter" data-level="3.3.5" data-path="inference.html"><a href="inference.html#question-5-2"><i class="fa fa-check"></i><b>3.3.5</b> Question 5</a></li>
<li class="chapter" data-level="3.3.6" data-path="inference.html"><a href="inference.html#question-6-2"><i class="fa fa-check"></i><b>3.3.6</b> Question 6</a></li>
<li class="chapter" data-level="3.3.7" data-path="inference.html"><a href="inference.html#question-7-2"><i class="fa fa-check"></i><b>3.3.7</b> Question 7</a></li>
<li class="chapter" data-level="3.3.8" data-path="inference.html"><a href="inference.html#question-8-2"><i class="fa fa-check"></i><b>3.3.8</b> Question 8</a></li>
<li class="chapter" data-level="3.3.9" data-path="inference.html"><a href="inference.html#question-9-2"><i class="fa fa-check"></i><b>3.3.9</b> Question 9</a></li>
<li class="chapter" data-level="3.3.10" data-path="inference.html"><a href="inference.html#question-10-1"><i class="fa fa-check"></i><b>3.3.10</b> Question 10</a></li>
<li class="chapter" data-level="3.3.11" data-path="inference.html"><a href="inference.html#question-11"><i class="fa fa-check"></i><b>3.3.11</b> Question 11</a></li>
<li class="chapter" data-level="3.3.12" data-path="inference.html"><a href="inference.html#question-12"><i class="fa fa-check"></i><b>3.3.12</b> Question 12</a></li>
<li class="chapter" data-level="3.3.13" data-path="inference.html"><a href="inference.html#question-13"><i class="fa fa-check"></i><b>3.3.13</b> Question 13</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="inference.html"><a href="inference.html#ch-2.13-exercises"><i class="fa fa-check"></i><b>3.4</b> Ch 2.13 Exercises</a><ul>
<li class="chapter" data-level="3.4.1" data-path="inference.html"><a href="inference.html#question-1-4"><i class="fa fa-check"></i><b>3.4.1</b> Question 1</a></li>
<li class="chapter" data-level="3.4.2" data-path="inference.html"><a href="inference.html#question-2-3"><i class="fa fa-check"></i><b>3.4.2</b> Question 2</a></li>
<li class="chapter" data-level="3.4.3" data-path="inference.html"><a href="inference.html#question-3-3"><i class="fa fa-check"></i><b>3.4.3</b> Question 3</a></li>
<li class="chapter" data-level="3.4.4" data-path="inference.html"><a href="inference.html#question-4-3"><i class="fa fa-check"></i><b>3.4.4</b> Question 4</a></li>
<li class="chapter" data-level="3.4.5" data-path="inference.html"><a href="inference.html#question-5-3"><i class="fa fa-check"></i><b>3.4.5</b> Question 5</a></li>
<li class="chapter" data-level="3.4.6" data-path="inference.html"><a href="inference.html#question-6-3"><i class="fa fa-check"></i><b>3.4.6</b> Question 6</a></li>
<li class="chapter" data-level="3.4.7" data-path="inference.html"><a href="inference.html#question-7-3"><i class="fa fa-check"></i><b>3.4.7</b> Question 7</a></li>
<li class="chapter" data-level="3.4.8" data-path="inference.html"><a href="inference.html#question-8-3"><i class="fa fa-check"></i><b>3.4.8</b> Question 8</a></li>
<li class="chapter" data-level="3.4.9" data-path="inference.html"><a href="inference.html#question-9-3"><i class="fa fa-check"></i><b>3.4.9</b> Question 9</a></li>
<li class="chapter" data-level="3.4.10" data-path="inference.html"><a href="inference.html#question-10-2"><i class="fa fa-check"></i><b>3.4.10</b> Question 10</a></li>
<li class="chapter" data-level="3.4.11" data-path="inference.html"><a href="inference.html#question-11-1"><i class="fa fa-check"></i><b>3.4.11</b> Question 11</a></li>
<li class="chapter" data-level="3.4.12" data-path="inference.html"><a href="inference.html#question-12-1"><i class="fa fa-check"></i><b>3.4.12</b> Question 12</a></li>
<li class="chapter" data-level="3.4.13" data-path="inference.html"><a href="inference.html#question-13-1"><i class="fa fa-check"></i><b>3.4.13</b> Question 13</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="inference.html"><a href="inference.html#ch-2.18-exercises"><i class="fa fa-check"></i><b>3.5</b> Ch 2.18 Exercises</a><ul>
<li class="chapter" data-level="3.5.1" data-path="inference.html"><a href="inference.html#question-1-5"><i class="fa fa-check"></i><b>3.5.1</b> Question 1</a></li>
<li class="chapter" data-level="3.5.2" data-path="inference.html"><a href="inference.html#question-2-4"><i class="fa fa-check"></i><b>3.5.2</b> Question 2</a></li>
<li class="chapter" data-level="3.5.3" data-path="inference.html"><a href="inference.html#question-3-4"><i class="fa fa-check"></i><b>3.5.3</b> Question 3</a></li>
<li class="chapter" data-level="3.5.4" data-path="inference.html"><a href="inference.html#question-4-4"><i class="fa fa-check"></i><b>3.5.4</b> Question 4</a></li>
<li class="chapter" data-level="3.5.5" data-path="inference.html"><a href="inference.html#question-5-4"><i class="fa fa-check"></i><b>3.5.5</b> Question 5</a></li>
<li class="chapter" data-level="3.5.6" data-path="inference.html"><a href="inference.html#question-6-4"><i class="fa fa-check"></i><b>3.5.6</b> Question 6</a></li>
<li class="chapter" data-level="3.5.7" data-path="inference.html"><a href="inference.html#question-7-4"><i class="fa fa-check"></i><b>3.5.7</b> Question 7</a></li>
<li class="chapter" data-level="3.5.8" data-path="inference.html"><a href="inference.html#question-8-4"><i class="fa fa-check"></i><b>3.5.8</b> Question 8</a></li>
<li class="chapter" data-level="3.5.9" data-path="inference.html"><a href="inference.html#question-9-4"><i class="fa fa-check"></i><b>3.5.9</b> Question 9</a></li>
<li class="chapter" data-level="3.5.10" data-path="inference.html"><a href="inference.html#question-10-3"><i class="fa fa-check"></i><b>3.5.10</b> Question 10</a></li>
<li class="chapter" data-level="3.5.11" data-path="inference.html"><a href="inference.html#question-11-2"><i class="fa fa-check"></i><b>3.5.11</b> Question 11</a></li>
<li class="chapter" data-level="3.5.12" data-path="inference.html"><a href="inference.html#question-12-2"><i class="fa fa-check"></i><b>3.5.12</b> Question 12</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="inference.html"><a href="inference.html#ch-2.21-exercises"><i class="fa fa-check"></i><b>3.6</b> Ch 2.21 Exercises</a><ul>
<li class="chapter" data-level="3.6.1" data-path="inference.html"><a href="inference.html#question-1-6"><i class="fa fa-check"></i><b>3.6.1</b> Question 1</a></li>
<li class="chapter" data-level="3.6.2" data-path="inference.html"><a href="inference.html#question-2-5"><i class="fa fa-check"></i><b>3.6.2</b> Question 2</a></li>
<li class="chapter" data-level="3.6.3" data-path="inference.html"><a href="inference.html#question-3-5"><i class="fa fa-check"></i><b>3.6.3</b> Question 3</a></li>
<li class="chapter" data-level="3.6.4" data-path="inference.html"><a href="inference.html#question-4-5"><i class="fa fa-check"></i><b>3.6.4</b> Question 4</a></li>
<li class="chapter" data-level="3.6.5" data-path="inference.html"><a href="inference.html#question-5-5"><i class="fa fa-check"></i><b>3.6.5</b> Question 5</a></li>
<li class="chapter" data-level="3.6.6" data-path="inference.html"><a href="inference.html#question-6-5"><i class="fa fa-check"></i><b>3.6.6</b> Question 6</a></li>
<li class="chapter" data-level="3.6.7" data-path="inference.html"><a href="inference.html#question-7-5"><i class="fa fa-check"></i><b>3.6.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="inference.html"><a href="inference.html#ch-2.23-exercises"><i class="fa fa-check"></i><b>3.7</b> Ch 2.23 Exercises</a><ul>
<li class="chapter" data-level="3.7.1" data-path="inference.html"><a href="inference.html#question-1-7"><i class="fa fa-check"></i><b>3.7.1</b> Question 1</a></li>
<li class="chapter" data-level="3.7.2" data-path="inference.html"><a href="inference.html#question-2-6"><i class="fa fa-check"></i><b>3.7.2</b> Question 2</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="inference.html"><a href="inference.html#ch-2.25-exercises"><i class="fa fa-check"></i><b>3.8</b> Ch 2.25 Exercises</a><ul>
<li class="chapter" data-level="3.8.1" data-path="inference.html"><a href="inference.html#question-1-8"><i class="fa fa-check"></i><b>3.8.1</b> Question 1</a></li>
<li class="chapter" data-level="3.8.2" data-path="inference.html"><a href="inference.html#question-2-7"><i class="fa fa-check"></i><b>3.8.2</b> Question 2</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis for the Life Sciences with R: Exercise Solutions (in progress)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inference" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Inference</h1>
<p>Note: I have rephrased some parts of the questions for clarity. These changes are <strong>bolded</strong>. The exact values of the answers, despite the same seeds, might differ. So please be mindful of that.</p>
<p>First, upload necessary package(s).</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1"><span class="kw">library</span>(tidyverse) <span class="co">#also uploads  dplyr</span></a>
<a class="sourceLine" id="cb2-2" title="2"><span class="kw">library</span>(rafalib) <span class="co"># important for plotting with base R</span></a></code></pre></div>
<div id="ch-2.7-exercises" class="section level2">
<h2><span class="header-section-number">3.1</span> Ch 2.7 Exercises</h2>
<p>If you have not downloaded the data before,</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">dir &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/&quot;</span></a>
<a class="sourceLine" id="cb3-2" title="2">filename &lt;-<span class="st"> &quot;femaleControlsPopulation.csv&quot;</span></a>
<a class="sourceLine" id="cb3-3" title="3">url &lt;-<span class="st"> </span><span class="kw">paste0</span>(dir, filename)</a>
<a class="sourceLine" id="cb3-4" title="4">x &lt;-<span class="st"> </span><span class="kw">unlist</span>(<span class="kw">read.csv</span>(url))</a></code></pre></div>
<p>Or if you already have downloaded the data, then just upload it.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1">dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;femaleControlsPopulation.csv&#39;</span>)</a>
<a class="sourceLine" id="cb4-2" title="2">bodyweight &lt;-<span class="st"> </span><span class="kw">select</span>(dat, Bodyweight)</a>
<a class="sourceLine" id="cb4-3" title="3">x &lt;-<span class="st"> </span><span class="kw">unlist</span>(bodyweight)</a>
<a class="sourceLine" id="cb4-4" title="4"></a>
<a class="sourceLine" id="cb4-5" title="5"><span class="co"># or use pipe %&gt;%</span></a>
<a class="sourceLine" id="cb4-6" title="6">x &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;femaleControlsPopulation.csv&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>()</a></code></pre></div>
<p>Check out what <code>unlist</code> does by typing <code>?unlist</code> in the command. The second method is more concise because of the pipe <code>%&gt;%</code>, which allows multiple lines of commands to be in one continuous line.</p>
<div id="question-1-1" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Question 1</h3>
<div class="question">
<p>What is the average of these weights?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">mean</span>(x)</a></code></pre></div>
<pre><code>## [1] 23.89338</code></pre>
</div>
<div id="question-2" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Question 2</h3>
<div class="question">
<p>After setting the seed at 1, <code>set.seed(1)</code> take a random sample size 5. What is the absolute value (use <code>abs</code>) of the difference between the average of the sample and the average of all the values?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb7-2" title="2">avg_sample &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">sample</span>(x,<span class="dv">5</span>)) <span class="co"># average of the sample of 5</span></a>
<a class="sourceLine" id="cb7-3" title="3">avg_pop &lt;-<span class="st"> </span><span class="kw">mean</span>(x) <span class="co"># average of all values</span></a>
<a class="sourceLine" id="cb7-4" title="4"><span class="kw">abs</span>(avg_sample <span class="op">-</span><span class="st"> </span>avg_pop) <span class="co"># absolute difference</span></a></code></pre></div>
<pre><code>## [1] 0.2706222</code></pre>
</div>
<div id="question-3" class="section level3">
<h3><span class="header-section-number">3.1.3</span> Question 3</h3>
<div class="question">
<p>After setting the seed at 5, <code>set.seed(5)</code> take a random sample size 5. What is the absolute value (use <code>abs</code>) of the difference between the average of the sample and the average of all the values?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="kw">set.seed</span>(<span class="dv">5</span>)</a>
<a class="sourceLine" id="cb9-2" title="2">avg_sample &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">sample</span>(x,<span class="dv">5</span>)) <span class="co"># average of the sample of 5</span></a>
<a class="sourceLine" id="cb9-3" title="3">avg_pop &lt;-<span class="st"> </span><span class="kw">mean</span>(x) <span class="co"># average of all values</span></a>
<a class="sourceLine" id="cb9-4" title="4"><span class="kw">abs</span>(avg_sample <span class="op">-</span><span class="st"> </span>avg_pop) <span class="co"># absolute difference</span></a></code></pre></div>
<pre><code>## [1] 1.433378</code></pre>
</div>
<div id="question-4" class="section level3">
<h3><span class="header-section-number">3.1.4</span> Question 4</h3>
<div class="question">
<p>Why are the answers from 2 and 3 different?</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>) <span class="co"># question 2</span></a>
<a class="sourceLine" id="cb11-2" title="2">a &lt;-<span class="st"> </span><span class="kw">sample</span>(x,<span class="dv">5</span>)</a>
<a class="sourceLine" id="cb11-3" title="3">a</a></code></pre></div>
<pre><code>##  Bodyweight60  Bodyweight84 Bodyweight128 Bodyweight202 
##         21.51         28.14         24.04         23.45 
##  Bodyweight45 
##         23.68</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="kw">set.seed</span>(<span class="dv">5</span>) <span class="co"># question 3</span></a>
<a class="sourceLine" id="cb13-2" title="2">b &lt;-<span class="st"> </span><span class="kw">sample</span>(x,<span class="dv">5</span>)</a>
<a class="sourceLine" id="cb13-3" title="3">b</a></code></pre></div>
<pre><code>##  Bodyweight46 Bodyweight154 Bodyweight205  Bodyweight64 
##         21.86         20.30         22.95         21.92 
##  Bodyweight24 
##         25.27</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">identical</span>(a,b) <span class="co"># these two samples are not identical</span></a></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Notice that samples <code>a</code> and <code>b</code> differ. Since the seeds were different (<code>1</code> vs <code>5</code>), different random numbers were generated. Therefore, the answer is <strong>C: Because the average of the samples is a random variable.</strong></p>
</div>
<div id="question-5" class="section level3">
<h3><span class="header-section-number">3.1.5</span> Question 5</h3>
<div class="question">
<p>Set the seed at 1, then using a for-loop take a random sample of 5 mice in 1,000 times. Save these averages. What percent of these 1,000 averages are more than 1 gram away from the average of <code>x</code>?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb17-2" title="2">n &lt;-<span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb17-3" title="3">res &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&#39;double&#39;</span>,n) </a>
<a class="sourceLine" id="cb17-4" title="4"></a>
<a class="sourceLine" id="cb17-5" title="5"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq</span>(n)) {</a>
<a class="sourceLine" id="cb17-6" title="6">  avg_sample &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">sample</span>(x,<span class="dv">5</span>))</a>
<a class="sourceLine" id="cb17-7" title="7">  res[[i]] &lt;-<span class="st"> </span>avg_sample</a>
<a class="sourceLine" id="cb17-8" title="8">}</a>
<a class="sourceLine" id="cb17-9" title="9"></a>
<a class="sourceLine" id="cb17-10" title="10"><span class="kw">mean</span>(<span class="kw">abs</span>(res<span class="op">-</span><span class="kw">mean</span>(x)) <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.498</code></pre>
<p>To make a for loop work in R, an empty vector needs to be created first. This can be achieved with the function <code>vector</code>. In this example, the empty vector is <code>res</code> (short for result). In the for loop, each average (<code>avg_sample</code>) from one repetition gets stored in <code>res</code>.</p>
</div>
<div id="question-6" class="section level3">
<h3><span class="header-section-number">3.1.6</span> Question 6</h3>
<div class="question">
<p>We are now going to increase the number of times we redo the sample from 1,000 to 10,000. Set the seed at 1, then using a for-loop take a random sample of 5 mice 10,000 times. Save these averages. What percent of these 10,000 averages are more than 1 gram away from the average of <code>x</code>?</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb19-2" title="2">n &lt;-<span class="st"> </span><span class="dv">10000</span></a>
<a class="sourceLine" id="cb19-3" title="3">res &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&#39;double&#39;</span>,n)</a>
<a class="sourceLine" id="cb19-4" title="4"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq</span>(n)) {</a>
<a class="sourceLine" id="cb19-5" title="5">  avg_sample &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">sample</span>(x,<span class="dv">5</span>))</a>
<a class="sourceLine" id="cb19-6" title="6">  res[[i]] &lt;-<span class="st"> </span>avg_sample</a>
<a class="sourceLine" id="cb19-7" title="7">}</a>
<a class="sourceLine" id="cb19-8" title="8"><span class="kw">mean</span>(<span class="kw">abs</span>(res<span class="op">-</span><span class="kw">mean</span>(x)) <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.4976</code></pre>
</div>
<div id="question-7" class="section level3">
<h3><span class="header-section-number">3.1.7</span> Question 7</h3>
<div class="question">
<p>Note that the answers to 5 and 6 barely changed. This is expected. The way we think about the random value distributions is as the distribution of the list of values obtained if we repeated the experiment an infinite number of times. On a computer, we can’t perform an infinite number of iterations so instead, for our examples, we consider 1,000 to be large enough, thus 10,000 is as well. Now if instead we change the sample size, then we change the random variable and thus its distribution.</p>
<p>Set the seed at 1, then using a for-loop take a random sample of 50 mice 1,000 times. Save these averages. What percent of these 1,000 averages are more than 1 gram away from the average of <code>x</code>?</p>
</div>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb21-2" title="2">n &lt;-<span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb21-3" title="3">res &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&#39;double&#39;</span>,n)</a>
<a class="sourceLine" id="cb21-4" title="4"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq</span>(n)) {</a>
<a class="sourceLine" id="cb21-5" title="5">  avg_sample &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">sample</span>(x,<span class="dv">50</span>))</a>
<a class="sourceLine" id="cb21-6" title="6">  res[[i]] &lt;-<span class="st"> </span>avg_sample</a>
<a class="sourceLine" id="cb21-7" title="7">}</a>
<a class="sourceLine" id="cb21-8" title="8"><span class="kw">mean</span>(<span class="kw">abs</span>(res<span class="op">-</span><span class="kw">mean</span>(x)) <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.019</code></pre>
</div>
<div id="question-8" class="section level3">
<h3><span class="header-section-number">3.1.8</span> Question 8</h3>
<div class="question">
<p>Use a histogram to “look” at the distribution of averages we get with a sample size of 5 and sample size of 50. How would you say they differ?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="co"># sample size = 5</span></a>
<a class="sourceLine" id="cb23-2" title="2"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb23-3" title="3">n &lt;-<span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb23-4" title="4">res5 &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&#39;double&#39;</span>,n)</a>
<a class="sourceLine" id="cb23-5" title="5"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq</span>(n)) {</a>
<a class="sourceLine" id="cb23-6" title="6">  avg_sample &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">sample</span>(x,<span class="dv">5</span>))</a>
<a class="sourceLine" id="cb23-7" title="7">  res5[[i]] &lt;-<span class="st"> </span>avg_sample</a>
<a class="sourceLine" id="cb23-8" title="8">}</a>
<a class="sourceLine" id="cb23-9" title="9"><span class="kw">sd</span>(res5) <span class="co"># standard deviation = spread of the histogram</span></a></code></pre></div>
<pre><code>## [1] 1.52445</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="co"># sample size = 50</span></a>
<a class="sourceLine" id="cb25-2" title="2"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb25-3" title="3">n &lt;-<span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb25-4" title="4">res50 &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&#39;double&#39;</span>,n)</a>
<a class="sourceLine" id="cb25-5" title="5"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq</span>(n)) {</a>
<a class="sourceLine" id="cb25-6" title="6">  avg_sample &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">sample</span>(x,<span class="dv">50</span>))</a>
<a class="sourceLine" id="cb25-7" title="7">  res50[[i]] &lt;-<span class="st"> </span>avg_sample</a>
<a class="sourceLine" id="cb25-8" title="8">}</a>
<a class="sourceLine" id="cb25-9" title="9"><span class="kw">sd</span>(res50) <span class="co"># standard deviation = spread of the histogram</span></a></code></pre></div>
<pre><code>## [1] 0.4260116</code></pre>
<p>The standard deviation of <code>res50</code> is smaller than that of <code>res5</code> because of the difference in the sample sizes. A higher standard deviation leads to a wider histogram. See two figures below.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="kw">mypar</span>(<span class="dv">1</span>,<span class="dv">2</span>) <span class="co"># plot histograms</span></a>
<a class="sourceLine" id="cb27-2" title="2"><span class="kw">hist</span>(res5)</a>
<a class="sourceLine" id="cb27-3" title="3"><span class="kw">hist</span>(res50)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p><code>mypar</code> is a function from the package <code>rafalib</code>. It helps to align multiple plots in a single plot. <code>mypar(1,1)</code> contains one panel only, <code>mypar(2,1)</code> contains 2 rows of panels and 1 column, <code>mypar(1,2)</code> contains 1 row of panels and 2 columns, etc. Type <code>?mypar</code> for more information. You will be using this function to plot a graph throughout the entire book. <code>hist</code> plots a histogram.</p>
<p>The answer is <strong>B: They both look normal, but with a sample size of 50 the spread is smaller.</strong></p>
</div>
<div id="question-9" class="section level3">
<h3><span class="header-section-number">3.1.9</span> Question 9</h3>
<div class="question">
<p>For the last set of averages, the ones obtained from a sample size of 50, what percent are between 23 and 25?</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="kw">mean</span>((res50 <span class="op">&gt;=</span><span class="dv">23</span>) <span class="op">&amp;</span><span class="st"> </span>(res50 <span class="op">&lt;=</span><span class="st"> </span><span class="dv">25</span>))</a></code></pre></div>
<pre><code>## [1] 0.976</code></pre>
</div>
<div id="question-10" class="section level3">
<h3><span class="header-section-number">3.1.10</span> Question 10</h3>
<div class="question">
<p>Now ask the same question of a normal distribution with average 23.9 and standard deviation 0.43.</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">pnorm</span>(<span class="dv">25</span>,<span class="fl">23.9</span>,<span class="fl">0.43</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="dv">23</span>,<span class="fl">23.9</span>,<span class="fl">0.43</span>)</a></code></pre></div>
<pre><code>## [1] 0.9765648</code></pre>
<p>The answers to 9 and 10 were very similar. This is because we can approximate the distribution of the sample average with a normal distribution. We will learn more about the reason for this next.</p>
</div>
</div>
<div id="ch-2.9-exercises" class="section level2">
<h2><span class="header-section-number">3.2</span> Ch 2.9 Exercises</h2>
<p>If you have not downloaded the data before:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1">dir &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/&quot;</span></a>
<a class="sourceLine" id="cb32-2" title="2">filename &lt;-<span class="st"> &quot;mice_pheno.csv&quot;</span></a>
<a class="sourceLine" id="cb32-3" title="3">url &lt;-<span class="st"> </span><span class="kw">paste0</span>(dir, filename)</a>
<a class="sourceLine" id="cb32-4" title="4">dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(url)</a>
<a class="sourceLine" id="cb32-5" title="5">dat &lt;-<span class="st"> </span><span class="kw">na.omit</span>(dat)</a></code></pre></div>
<p>If you have the data already in your directory:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1">raw_data &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;mice_pheno.csv&#39;</span>)</a>
<a class="sourceLine" id="cb33-2" title="2">dat &lt;-<span class="st"> </span><span class="kw">na.omit</span>(raw_data)</a></code></pre></div>
<div id="question-1-2" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Question 1</h3>
<div class="question">
<p>Use <code>dplyr</code> to create a vector x with the body weight of all males on the control (chow) diet. What is this population’s average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1">x &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;M&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;chow&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb34-2" title="2"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>()</a>
<a class="sourceLine" id="cb34-3" title="3"><span class="kw">mean</span>(x)</a></code></pre></div>
<pre><code>## [1] 30.96381</code></pre>
<p>Throughout the book, I will be using <code>%&gt;%</code> for brevity. If you don’t understand it, please check out Chapter 18 of <a href="https://r4ds.had.co.nz/pipes.html">*R for Data Science</a>.</p>
</div>
<div id="question-2-1" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Question 2</h3>
<div class="question">
<p>Now use the <code>rafalib</code> package and use the <code>popsd</code> function to compute the population standard deviation.</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">popsd</span>(x)</a></code></pre></div>
<pre><code>## [1] 4.420501</code></pre>
<p><code>popsd</code> and <code>sd</code> are slightly different. <code>sd</code> calculates the standard deviation of the sample size, so the denominator that it uses to compute SD is <code>n-1</code>. Function <code>var</code> also uses denominator <code>n-1</code> to calculate variance. However, <code>popsd</code> (which is from <code>rafalib</code> package) uses denominator <code>n</code>.</p>
</div>
<div id="question-3-1" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Question 3</h3>
<div class="question">
<p>Set the seed at 1. Take a random sample X of size 25 from x. What is the sample average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb38-2" title="2">samp_x &lt;-<span class="st"> </span><span class="kw">sample</span>(x,<span class="dv">25</span>) <span class="co"># sample of x</span></a>
<a class="sourceLine" id="cb38-3" title="3"><span class="kw">mean</span>(samp_x)</a></code></pre></div>
<pre><code>## [1] 32.0956</code></pre>
</div>
<div id="question-4-1" class="section level3">
<h3><span class="header-section-number">3.2.4</span> Question 4</h3>
<div class="question">
<p>Use <code>dplyr</code> to create a vector <code>y</code> with the body weight of all males on the high fat (hf) diet. What is this population’s average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1">y &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;M&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;hf&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb40-2" title="2"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>()</a>
<a class="sourceLine" id="cb40-3" title="3"><span class="kw">mean</span>(y)</a></code></pre></div>
<pre><code>## [1] 34.84793</code></pre>
</div>
<div id="question-5-1" class="section level3">
<h3><span class="header-section-number">3.2.5</span> Question 5</h3>
<div class="question">
<p>Now use the <code>rafalib</code> package and use the <code>popsd</code> function to compute the population standard deviation.</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1"><span class="kw">popsd</span>(y)</a></code></pre></div>
<pre><code>## [1] 5.574609</code></pre>
</div>
<div id="question-6-1" class="section level3">
<h3><span class="header-section-number">3.2.6</span> Question 6</h3>
<div class="question">
<p>Set the seed at 1. Take a random sample Y of size 25 from y. What is the sample average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb44-2" title="2">samp_y &lt;-<span class="st"> </span><span class="kw">sample</span>(y,<span class="dv">25</span>)</a>
<a class="sourceLine" id="cb44-3" title="3"><span class="kw">mean</span>(samp_y)</a></code></pre></div>
<pre><code>## [1] 34.768</code></pre>
</div>
<div id="question-7-1" class="section level3">
<h3><span class="header-section-number">3.2.7</span> Question 7</h3>
<div class="question">
<p>What is the difference in absolute value between <span class="math inline">\(\bar{y}-\bar{x}\)</span> and <span class="math inline">\(\bar{Y}-\bar{X}\)</span>?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1">pop_diff &lt;-<span class="st"> </span><span class="kw">mean</span>(y) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(x)</a>
<a class="sourceLine" id="cb46-2" title="2">sample_diff &lt;-<span class="st"> </span><span class="kw">mean</span>(samp_y) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(samp_x)</a>
<a class="sourceLine" id="cb46-3" title="3"><span class="kw">abs</span>(sample_diff <span class="op">-</span><span class="st"> </span>pop_diff)</a></code></pre></div>
<pre><code>## [1] 1.211716</code></pre>
</div>
<div id="question-8-1" class="section level3">
<h3><span class="header-section-number">3.2.8</span> Question 8</h3>
<div class="question">
<p>Repeat the above for females. Make sure to set the seed to 1 before each <code>sample</code> call. What is the difference in absolute value between <span class="math inline">\(\bar{y}-\bar{x}\)</span> and <span class="math inline">\(\bar{Y}-\bar{X}\)</span>?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1">chow_f_pop &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;F&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;chow&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb48-2" title="2"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>() <span class="co"># x</span></a>
<a class="sourceLine" id="cb48-3" title="3">hf_f_pop &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;F&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;hf&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb48-4" title="4"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>() <span class="co"># y</span></a>
<a class="sourceLine" id="cb48-5" title="5"></a>
<a class="sourceLine" id="cb48-6" title="6"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb48-7" title="7">sample_chow_f_pop &lt;-<span class="st"> </span><span class="kw">sample</span>(chow_f_pop, <span class="dv">25</span>) <span class="co"># X</span></a>
<a class="sourceLine" id="cb48-8" title="8"></a>
<a class="sourceLine" id="cb48-9" title="9"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb48-10" title="10">sample_hf_f_pop &lt;-<span class="st"> </span><span class="kw">sample</span>(hf_f_pop,<span class="dv">25</span>) <span class="co"># Y</span></a>
<a class="sourceLine" id="cb48-11" title="11"></a>
<a class="sourceLine" id="cb48-12" title="12">pop_diff &lt;-<span class="st"> </span><span class="kw">mean</span>(hf_f_pop) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(chow_f_pop) <span class="co"># y - x</span></a>
<a class="sourceLine" id="cb48-13" title="13">sample_diff &lt;-<span class="st"> </span><span class="kw">mean</span>(sample_hf_f_pop) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(sample_chow_f_pop) <span class="co"># Y - X</span></a>
<a class="sourceLine" id="cb48-14" title="14"></a>
<a class="sourceLine" id="cb48-15" title="15"><span class="kw">abs</span>(sample_diff <span class="op">-</span><span class="st"> </span>pop_diff)</a></code></pre></div>
<pre><code>## [1] 0.7364828</code></pre>
</div>
<div id="question-9-1" class="section level3">
<h3><span class="header-section-number">3.2.9</span> Question 9</h3>
<div class="question">
<p>For the females, our sample estimates were closer to the population difference than with males. What is a possible explanation for this?</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1">ans &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">popsd</span>(hf_f_pop), <span class="kw">popsd</span>(chow_f_pop), <span class="kw">popsd</span>(y), <span class="kw">popsd</span>(x))</a>
<a class="sourceLine" id="cb50-2" title="2"><span class="kw">names</span>(ans) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;hf female&#39;</span>, <span class="st">&#39;chow female&#39;</span>, <span class="st">&#39;hf male&#39;</span>, <span class="st">&#39;chow male&#39;</span>)</a>
<a class="sourceLine" id="cb50-3" title="3">ans</a></code></pre></div>
<pre><code>##   hf female chow female     hf male   chow male 
##    5.069870    3.416438    5.574609    4.420501</code></pre>
<p>The answer is <strong>A: The population variance of the females is smaller than that of the males; thus, the sample variable has less variability.</strong></p>
</div>
</div>
<div id="ch-2.11-exercises" class="section level2">
<h2><span class="header-section-number">3.3</span> Ch 2.11 Exercises</h2>
<p>If you have not downloaded the data before:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">dir &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/&quot;</span></a>
<a class="sourceLine" id="cb52-2" title="2">filename &lt;-<span class="st"> &quot;mice_pheno.csv&quot;</span></a>
<a class="sourceLine" id="cb52-3" title="3">url &lt;-<span class="st"> </span><span class="kw">paste0</span>(dir, filename)</a>
<a class="sourceLine" id="cb52-4" title="4">dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(url)</a>
<a class="sourceLine" id="cb52-5" title="5">dat &lt;-<span class="st"> </span><span class="kw">na.omit</span>(dat)</a></code></pre></div>
<p>If you have the data already in your directory:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1">raw_data &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;mice_pheno.csv&#39;</span>)</a>
<a class="sourceLine" id="cb53-2" title="2">dat &lt;-<span class="st"> </span><span class="kw">na.omit</span>(raw_data)</a></code></pre></div>
<div id="question-1-3" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Question 1</h3>
<div class="question">
<p>If a list of numbers has a distribution that is well approximated by the normal distribution, what proportion of these numbers are within one standard deviation away from the list’s average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">pnorm</span>(<span class="dv">1</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.6826895</code></pre>
</div>
<div id="question-2-2" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Question 2</h3>
<div class="question">
<p>What proportion of these numbers are within two standard deviations away from the list’s average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="kw">pnorm</span>(<span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span><span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 0.9544997</code></pre>
</div>
<div id="question-3-2" class="section level3">
<h3><span class="header-section-number">3.3.3</span> Question 3</h3>
<div class="question">
<p>What proportion of these numbers are within three standard deviations away from the list’s average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw">pnorm</span>(<span class="dv">3</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span><span class="dv">3</span>)</a></code></pre></div>
<pre><code>## [1] 0.9973002</code></pre>
</div>
<div id="question-4-2" class="section level3">
<h3><span class="header-section-number">3.3.4</span> Question 4</h3>
<div class="question">
<p>Define <code>y</code> to be the weights of males on the control diet. What proportion of the mice are within one standard deviation away from the average weight (remember to use <code>popsd</code> for the population <code>sd</code>)?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1">y &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;M&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;chow&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb60-2" title="2"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>()</a>
<a class="sourceLine" id="cb60-3" title="3"></a>
<a class="sourceLine" id="cb60-4" title="4">z_score &lt;-<span class="st"> </span>(y <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(y))<span class="op">/</span><span class="kw">popsd</span>(y) <span class="co"># get t-statistic (i.e., z score)</span></a>
<a class="sourceLine" id="cb60-5" title="5"><span class="kw">mean</span>(<span class="kw">abs</span>(z_score) <span class="op">&lt;=</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.6950673</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="kw">mean</span>(<span class="kw">abs</span>(y <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(y)) <span class="op">&lt;=</span><span class="st"> </span><span class="kw">popsd</span>(y))</a></code></pre></div>
<pre><code>## [1] 0.6950673</code></pre>
<p>It doesn’t matter which solution you use as long as you have the same answer.</p>
</div>
<div id="question-5-2" class="section level3">
<h3><span class="header-section-number">3.3.5</span> Question 5</h3>
<div class="question">
<p>What proportion of these numbers are within two standard deviations away from the list’s average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="kw">mean</span>(<span class="kw">abs</span>(z_score) <span class="op">&lt;=</span><span class="st"> </span><span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 0.9461883</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1"><span class="kw">mean</span>(<span class="kw">abs</span>(y <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(y)) <span class="op">&lt;=</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span><span class="kw">popsd</span>(y))</a></code></pre></div>
<pre><code>## [1] 0.9461883</code></pre>
<p>It doesn’t matter which solution you use as long as you have the same answer.</p>
</div>
<div id="question-6-2" class="section level3">
<h3><span class="header-section-number">3.3.6</span> Question 6</h3>
<div class="question">
<p>What proportion of these numbers are within three standard deviations away from the list’s average?</p>
</div>
<div class="answer">



<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="kw">mean</span>(<span class="kw">abs</span>(z_score) <span class="op">&lt;=</span><span class="st"> </span><span class="dv">3</span>)</a></code></pre></div>
<pre><code>## [1] 0.9910314</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="kw">mean</span>(<span class="kw">abs</span>(y <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(y)) <span class="op">&lt;=</span><span class="st"> </span><span class="dv">3</span><span class="op">*</span><span class="kw">popsd</span>(y))</a></code></pre></div>
<pre><code>## [1] 0.9910314</code></pre>
<p>It doesn’t matter which solution you use as long as you have the same answer.</p>
</div>
<div id="question-7-2" class="section level3">
<h3><span class="header-section-number">3.3.7</span> Question 7</h3>
<div class="question">
<p>Note that the numbers for the normal distribution and our weights are relatively close. Also, notice that we are indirectly comparing quantiles of the normal distribution to quantiles of the mouse weight distribution. We can actually compare all quantiles using a qq-plot. Which of the following best describes the qq-plot comparing mouse weights to the normal distribution?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">mypar</span>(<span class="dv">1</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb72-2" title="2"><span class="kw">qqnorm</span>(y)</a>
<a class="sourceLine" id="cb72-3" title="3"><span class="kw">qqline</span>(y)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>The answer is <strong>C: The mouse weights are well approximated by the normal distribution, although the larger values (right tail) are larger than predicted by the normal.This is consistent with the differences seen between question 3 and 6.</strong></p>
</div>
<div id="question-8-2" class="section level3">
<h3><span class="header-section-number">3.3.8</span> Question 8</h3>
<div class="question">
<p>Create the above qq-plot for the four populations: male/females on each of the two diets. What is the most likely explanation for the mouse weights being well approximated? What is the best explanation for all these being well approximated by the normal distribution?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1">mc &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;M&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;chow&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb73-2" title="2"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>()</a>
<a class="sourceLine" id="cb73-3" title="3">mhf &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;M&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;hf&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb73-4" title="4"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>()</a>
<a class="sourceLine" id="cb73-5" title="5">fc &lt;-<span class="st"> </span>y &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;F&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;chow&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb73-6" title="6"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>()</a>
<a class="sourceLine" id="cb73-7" title="7">fhf &lt;-<span class="st"> </span>y &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Sex <span class="op">==</span><span class="st"> &#39;F&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Diet <span class="op">==</span><span class="st"> &#39;hf&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb73-8" title="8"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unlist</span>()</a>
<a class="sourceLine" id="cb73-9" title="9"></a>
<a class="sourceLine" id="cb73-10" title="10"><span class="kw">mypar</span>(<span class="dv">2</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb73-11" title="11"><span class="kw">qqnorm</span>(mc, <span class="dt">main =</span> <span class="st">&#39;male control pop&#39;</span>)</a>
<a class="sourceLine" id="cb73-12" title="12"><span class="kw">qqline</span>(mc)</a>
<a class="sourceLine" id="cb73-13" title="13"><span class="kw">qqnorm</span>(mhf, <span class="dt">main =</span> <span class="st">&#39;male high fat pop&#39;</span>)</a>
<a class="sourceLine" id="cb73-14" title="14"><span class="kw">qqline</span>(mhf)</a>
<a class="sourceLine" id="cb73-15" title="15"><span class="kw">qqnorm</span>(fc, <span class="dt">main =</span> <span class="st">&#39;female control pop&#39;</span>)</a>
<a class="sourceLine" id="cb73-16" title="16"><span class="kw">qqline</span>(fc)</a>
<a class="sourceLine" id="cb73-17" title="17"><span class="kw">qqnorm</span>(fhf, <span class="dt">main =</span> <span class="st">&#39;female high fat pop&#39;</span>)</a>
<a class="sourceLine" id="cb73-18" title="18"><span class="kw">qqline</span>(fhf)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>The answer is <strong>B: This just happens to be how nature behaves. Perhaps the result of many biological factors averaging out.</strong></p>
</div>
<div id="question-9-2" class="section level3">
<h3><span class="header-section-number">3.3.9</span> Question 9</h3>
<div class="question">
<p>Here we are going to use the function <code>replicate</code> to learn about the distribution of random variables. All the above exercises relate to the normal distribution as an approximation of the distribution of a fixed list of numbers or a population. We have not yet discussed probability in these exercises. If the distribution of a list of numbers is approximately normal, then if we pick a number at random from
this distribution, it will follow a normal distribution. However, it is important to remember that stating that some quantity has a distribution does not necessarily imply this quantity is random. Also, keep in mind that this is not related to the central limit theorem. The central limit applies to averages of random variables. Let’s explore this concept.</p>
<p>We will now take a sample of size 25 from the population of males on the chow diet. The average of this sample is our random variable. We will use the <code>replicate</code> to observe 10,000 realizations of this random variable. Set the seed at 1, generate these 10,000 averages. Make a histogram and qq-plot of these 10,000 numbers against the normal distribution.</p>
<p>We can see that, as predicted by the CLT, the distribution of the random variable is very well approximated by the normal distribution.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1">y &lt;-<span class="st"> </span><span class="kw">filter</span>(dat, Sex<span class="op">==</span><span class="st">&quot;M&quot;</span> <span class="op">&amp;</span><span class="st"> </span>Diet<span class="op">==</span><span class="st">&quot;chow&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span>unlist</a>
<a class="sourceLine" id="cb74-2" title="2">avgs &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">10000</span>, <span class="kw">mean</span>( <span class="kw">sample</span>(y, <span class="dv">25</span>)))</a>
<a class="sourceLine" id="cb74-3" title="3"><span class="kw">mypar</span>(<span class="dv">1</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb74-4" title="4"><span class="kw">hist</span>(avgs)</a>
<a class="sourceLine" id="cb74-5" title="5"><span class="kw">qqnorm</span>(avgs)</a>
<a class="sourceLine" id="cb74-6" title="6"><span class="kw">qqline</span>(avgs)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>What is the average of the distribution of the sample average?</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1">m &lt;-<span class="st"> </span><span class="dv">10000</span></a>
<a class="sourceLine" id="cb75-2" title="2">n &lt;-<span class="st"> </span><span class="dv">25</span></a>
<a class="sourceLine" id="cb75-3" title="3">y &lt;-<span class="st"> </span><span class="kw">filter</span>(dat, Sex<span class="op">==</span><span class="st">&quot;M&quot;</span> <span class="op">&amp;</span><span class="st"> </span>Diet<span class="op">==</span><span class="st">&quot;chow&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb75-4" title="4"><span class="st">  </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span>unlist</a>
<a class="sourceLine" id="cb75-5" title="5"></a>
<a class="sourceLine" id="cb75-6" title="6"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb75-7" title="7">avg_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(m, {</a>
<a class="sourceLine" id="cb75-8" title="8">  <span class="kw">mean</span>(<span class="kw">sample</span>(y,<span class="dv">25</span>))</a>
<a class="sourceLine" id="cb75-9" title="9">})</a>
<a class="sourceLine" id="cb75-10" title="10"></a>
<a class="sourceLine" id="cb75-11" title="11"><span class="kw">mypar</span>(<span class="dv">1</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb75-12" title="12"><span class="kw">hist</span>(avg_list) <span class="co"># distribution</span></a>
<a class="sourceLine" id="cb75-13" title="13"><span class="kw">qqnorm</span>(avg_list) <span class="co"># qq-plot</span></a>
<a class="sourceLine" id="cb75-14" title="14"><span class="kw">qqline</span>(avg_list)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">mean</span>(avg_list) <span class="co"># mean of the sample averages</span></a></code></pre></div>
<pre><code>## [1] 30.95581</code></pre>
</div>
<div id="question-10-1" class="section level3">
<h3><span class="header-section-number">3.3.10</span> Question 10</h3>
<div class="question">
<p>What is the standard deviation of the distribution of sample averages?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1"><span class="kw">popsd</span>(avg_list)</a></code></pre></div>
<pre><code>## [1] 0.8368192</code></pre>
</div>
<div id="question-11" class="section level3">
<h3><span class="header-section-number">3.3.11</span> Question 11</h3>
<div class="question">
<p>According to the CLT, the answer to exercise 9 should be the same as <code>mean(y)</code>. You should be able to confirm that these two numbers are very close. Which of the following does the CLT tell us should be close to your answer to exercise 10?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1"><span class="kw">popsd</span>(y)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">25</span>) <span class="co"># answer is C</span></a></code></pre></div>
<pre><code>## [1] 0.8841001</code></pre>
</div>
<div id="question-12" class="section level3">
<h3><span class="header-section-number">3.3.12</span> Question 12</h3>
<div class="question">
<p>In practice we do not know <span class="math inline">\(\sigma\)</span> (<code>popsd(y)</code>) which is why we can’t use the CLT directly. This is because we see a sample and not the entire distribution. We also
can’t use <code>popsd(avgs)</code> because to construct averages, we have to take 10,000 samples and this is never practical. We usually just get one sample. Instead we have to estimate <code>popsd(y)</code>. As described, what we use is the sample standard
deviation. Set the seed at 1, using the <code>replicate</code> function, create 10,000 samples of 25 and now, instead of the sample average, keep the standard deviation. Look at the distribution of the sample standard deviations. It is a random variable. The real population SD is about 4.5. What proportion of the sample SDs are below 3.5?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1">m &lt;-<span class="st"> </span><span class="dv">10000</span></a>
<a class="sourceLine" id="cb82-2" title="2"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb82-3" title="3">sd_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(m, {</a>
<a class="sourceLine" id="cb82-4" title="4">  <span class="kw">sd</span>(<span class="kw">sample</span>(y,<span class="dv">25</span>))</a>
<a class="sourceLine" id="cb82-5" title="5">})</a>
<a class="sourceLine" id="cb82-6" title="6"><span class="kw">mypar</span>(<span class="dv">1</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb82-7" title="7"><span class="kw">hist</span>(sd_list)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1"><span class="kw">mean</span>(sd_list <span class="op">&lt;=</span><span class="st"> </span><span class="fl">3.5</span>)</a></code></pre></div>
<pre><code>## [1] 0.0964</code></pre>
</div>
<div id="question-13" class="section level3">
<h3><span class="header-section-number">3.3.13</span> Question 13</h3>
<div class="question">
<p>What the answer to question 12 reveals is that the denominator of the t-test is a random variable. By decreasing the sample size, you can see how this variability can increase. It therefore adds variability. The smaller the sample size, the more variability is added. The normal distribution stops providing a useful approximation. When the distribution of the population values is approximately normal, as it is for the weights, the t-distribution provides a better approximation. We will see this later on. Here we will look at the difference between the t-distribution and normal. Use the function <code>qt</code> and <code>qnorm</code> to get the quantiles of <code>x=seq(0.0001,0.9999,len=300)</code>. Do this for degrees of freedom 3, 10, 30, and 100. Which of the following is true?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1">x =<span class="st"> </span><span class="kw">seq</span>(<span class="fl">0.0001</span>, <span class="fl">0.9999</span>, <span class="dt">len =</span> <span class="dv">300</span>)</a>
<a class="sourceLine" id="cb85-2" title="2">df_list &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">10</span>,<span class="dv">30</span>,<span class="dv">100</span>)</a>
<a class="sourceLine" id="cb85-3" title="3"><span class="kw">mypar</span>(<span class="dv">2</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb85-4" title="4"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(df_list)) {</a>
<a class="sourceLine" id="cb85-5" title="5">  <span class="kw">qqnorm</span>(<span class="kw">qt</span>(x,df_list[i]), <span class="dt">main =</span> df_list[i])</a>
<a class="sourceLine" id="cb85-6" title="6">}</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>The answer is <strong>C: The t-distribution has larger tails up until 30 degrees of freedom, at which point it is practically the same as the normal distribution.</strong></p>
</div>
</div>
<div id="ch-2.13-exercises" class="section level2">
<h2><span class="header-section-number">3.4</span> Ch 2.13 Exercises</h2>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1">dir &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/&quot;</span></a>
<a class="sourceLine" id="cb86-2" title="2">filename &lt;-<span class="st"> &quot;femaleMiceWeights.csv&quot;</span></a>
<a class="sourceLine" id="cb86-3" title="3">url &lt;-<span class="st"> </span><span class="kw">paste0</span>(dir, filename)</a>
<a class="sourceLine" id="cb86-4" title="4">dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(url)</a></code></pre></div>
<div id="question-1-4" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Question 1</h3>
<div class="question">
<p>The CLT is a result from probability theory. Much of probability theory was originally inspired by gambling. This theory is still used in practice by casinos. For example, they can estimate how many people need to play slots for there to be a 99.9999% probability of earning enough money to cover expenses. Let’s try a simple example related to gambling.</p>
<p>Suppose we are interested in the proportion of times we see a 6 when rolling n=100 die. This is a random variable which we can simulate with <code>x=sample(1:6, n, replace=TRUE)</code> and the proportion we are interested in can be expressed as an average: <code>mean(x==6)</code>. Because the die rolls are independent, the CLT applies.</p>
<p>We want to roll <code>n</code> dice 10,000 times and keep these proportions. This random variable (proportion of 6s) has mean <code>p=1/6</code> and variance <code>p*(1-p)/n</code>. So according to CLT
<code>z = (mean(x==6) - p) / sqrt(p*(1-p)/n)</code> should be normal with mean 0 and SD 1. Set the seed to 1, then use replicate to perform the simulation, and report what proportion of
times <code>z</code> was larger than 2 in absolute value (CLT says it should be about 0.05).</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1">n &lt;-<span class="st"> </span><span class="dv">100</span></a>
<a class="sourceLine" id="cb87-2" title="2">B &lt;-<span class="st"> </span><span class="dv">10000</span></a>
<a class="sourceLine" id="cb87-3" title="3">p &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">/</span><span class="dv">6</span></a>
<a class="sourceLine" id="cb87-4" title="4"></a>
<a class="sourceLine" id="cb87-5" title="5"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb87-6" title="6">res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(B, {</a>
<a class="sourceLine" id="cb87-7" title="7">  x =<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>,n, <span class="dt">replace =</span> T)</a>
<a class="sourceLine" id="cb87-8" title="8">  z &lt;-<span class="st"> </span>(<span class="kw">mean</span>(x<span class="op">==</span><span class="dv">6</span>)<span class="op">-</span>p) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(p<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p)<span class="op">/</span>n)</a>
<a class="sourceLine" id="cb87-9" title="9">  <span class="kw">return</span>(z)</a>
<a class="sourceLine" id="cb87-10" title="10">})</a>
<a class="sourceLine" id="cb87-11" title="11"><span class="kw">mean</span>(<span class="kw">abs</span>(res_list) <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 0.0424</code></pre>
</div>
<div id="question-2-3" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Question 2</h3>
<div class="question">
<p>For the last simulation you can make a qqplot to confirm the normal approximation. Now, the CLT is an asymptotic result, meaning it is closer and closer to being a perfect approximation as the sample size increases. In practice, however, we need to decide if it is appropriate for actual sample sizes. Is 10 enough? 15? 30?</p>
<p>In the example used in exercise 1, the original data is binary (either 6 or not). In this case, the success probability also affects the appropriateness of the CLT. With very low probabilities, we need larger sample sizes for the CLT to “kick in”.</p>
<p>Run the simulation from exercise 1, but for different values of <code>p</code> and <code>n</code>. For which of the following is the normal approximation best?</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1">Ps &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.01</span>,<span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb89-2" title="2">Ns &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">30</span>,<span class="dv">100</span>)</a>
<a class="sourceLine" id="cb89-3" title="3"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb89-4" title="4">question2 &lt;-<span class="st"> </span><span class="cf">function</span>(n,p, <span class="dt">B =</span> <span class="dv">10000</span>) {</a>
<a class="sourceLine" id="cb89-5" title="5">  res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(B, {</a>
<a class="sourceLine" id="cb89-6" title="6">    sides &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">/</span>p</a>
<a class="sourceLine" id="cb89-7" title="7">    x =<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span>sides, n, <span class="dt">replace =</span> T)</a>
<a class="sourceLine" id="cb89-8" title="8">    z &lt;-<span class="st"> </span>(<span class="kw">mean</span>(x<span class="op">==</span><span class="dv">1</span>)<span class="op">-</span>p) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(p<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p)<span class="op">/</span>n)</a>
<a class="sourceLine" id="cb89-9" title="9">    <span class="kw">return</span>(z)</a>
<a class="sourceLine" id="cb89-10" title="10">  })</a>
<a class="sourceLine" id="cb89-11" title="11">}</a>
<a class="sourceLine" id="cb89-12" title="12"><span class="kw">mypar</span>(<span class="dv">2</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb89-13" title="13"><span class="kw">qqnorm</span>(<span class="kw">question2</span>(<span class="dv">5</span>,<span class="fl">0.5</span>), <span class="dt">main =</span> <span class="st">&#39;n=5, p=0.5&#39;</span>)</a>
<a class="sourceLine" id="cb89-14" title="14"><span class="kw">qqnorm</span>(<span class="kw">question2</span>(<span class="dv">30</span>,<span class="fl">0.5</span>), <span class="dt">main =</span> <span class="st">&#39;n=30, p=0.5&#39;</span>) <span class="co"># the answer is B</span></a>
<a class="sourceLine" id="cb89-15" title="15"><span class="kw">qqnorm</span>(<span class="kw">question2</span>(<span class="dv">30</span>,<span class="fl">0.01</span>), <span class="dt">main =</span> <span class="st">&#39;n=30, p=0.01&#39;</span>)</a>
<a class="sourceLine" id="cb89-16" title="16"><span class="kw">qqnorm</span>(<span class="kw">question2</span>(<span class="dv">100</span>,<span class="fl">0.01</span>), <span class="dt">main =</span> <span class="st">&#39;n=100, p=0.01&#39;</span>)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1"><span class="kw">mypar</span>(<span class="dv">1</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb90-2" title="2"><span class="kw">hist</span>(<span class="kw">question2</span>(<span class="dv">30</span>,<span class="fl">0.5</span>), <span class="dt">main =</span> <span class="st">&#39;n=30, p=0.5&#39;</span>)</a>
<a class="sourceLine" id="cb90-3" title="3"><span class="kw">hist</span>(<span class="kw">question2</span>(<span class="dv">100</span>,<span class="fl">0.01</span>), <span class="dt">main =</span> <span class="st">&#39;n=100, p=0.01&#39;</span>)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-51-2.png" width="672" /></p>
<p>The answer is <strong>B, n = 30, p = 0.5.</strong> I created a custom function for this question. However, another approach (and maybe more concise) is to use a for loop.</p>
<p>This is tricky question, primarily because not all dice has number 6 (as is the case in Question 1, <code>mean(x==6)</code>). So you had to calculate the probability where the dice ends up in another side by modifying the code; since all dice has sdie 1, <code>mean(x==1)</code> seems like a safe choice. Also, the number of the sides for each die changes since it is defined by the <code>p</code> value. For instance, if <code>p</code> equals <code>0.01</code> for side 1, then there are 100 sides total (<code>1/0.01 = 100</code>).</p>
</div>
<div id="question-3-3" class="section level3">
<h3><span class="header-section-number">3.4.3</span> Question 3</h3>
<div class="question">
<p>As we have already seen, the CLT also applies to averages of quantitative data. A major difference with binary data, for which we know the variance is p(1-p), is that with quantitative data we need to estimate the population standard
deviation.</p>
<p>In several previous exercises we have illustrated statistical concepts with the unrealistic situation of having access to the entire population. In practice, we do not have access to
entire populations. Instead, we obtain one random sample and need to reach conclusions analyzing that data. dat is an example of a typical simple dataset representing just one
sample. We have 12 measurements for each of two populations:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" title="1">X &lt;-<span class="st"> </span><span class="kw">filter</span>(dat, Diet<span class="op">==</span><span class="st">&quot;chow&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span>unlist</a>
<a class="sourceLine" id="cb91-2" title="2">Y &lt;-<span class="st"> </span><span class="kw">filter</span>(dat, Diet<span class="op">==</span><span class="st">&quot;hf&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(Bodyweight) <span class="op">%&gt;%</span><span class="st"> </span>unlist</a></code></pre></div>
<p>We think of X as a random sample from the population of all mice in the control diet and Y as a random sample from the population of all mice in the high fat diet.
Define the parameter <span class="math inline">\(\mu_x\)</span> as the average of the control population. We estimate this parameter with the sample average <span class="math inline">\(\bar{X}\)</span>. What is the sample average?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1"><span class="kw">mean</span>(X)</a></code></pre></div>
<pre><code>## [1] 23.81333</code></pre>
</div>
<div id="question-4-3" class="section level3">
<h3><span class="header-section-number">3.4.4</span> Question 4</h3>
<div class="question">
<p>We don’t know <span class="math inline">\(\mu_x\)</span>, but want to use <span class="math inline">\(\bar{X}\)</span> to understand <span class="math inline">\(\mu_x\)</span>. Which of the following uses CLT to understand how well <span class="math inline">\(\bar{X}\)</span> approximates <span class="math inline">\(\mu_x\)</span>?</p>
</div>
<div class="answer">

<p>The answer is <strong>D: <span class="math inline">\(\bar{X}\)</span> follows a normal distribution with mean <span class="math inline">\(\mu_x\)</span> and standard deviation of <span class="math inline">\(\frac{\sigma_x}{\sqrt{12}}\)</span> where <span class="math inline">\(\sigma_x\)</span> is the population of standard deviation.</strong></p>
<p>It is important to be aware of the fact that <span class="math inline">\(\bar{X}\)</span> is based on raw data. So the mean of the distribution can be approximated by the population mean <span class="math inline">\(\mu_x\)</span>. However, if the question asked about z-score, then it would be at 0, because z-score (i.e., t-statistic) is standardized.</p>
</div>
<div id="question-5-3" class="section level3">
<h3><span class="header-section-number">3.4.5</span> Question 5</h3>
<div class="question">
<p>The result above tells us the distribution of the following random variable <span class="math inline">\(Z = \sqrt{12}\frac{\bar{X}-\mu_x}{\sigma_x}\)</span>. What does the CLT tell us is the mean of <span class="math inline">\(Z\)</span> (you don’t need code)?</p>
</div>
<div class="answer">

<p>The answer is <strong>0</strong>. Z refers to t-statistic (something that the book does not explicitly highlight), which is not raw data. Instead, we use raw data and then compute t-statistic. This is the value that is used to compute p-value based on the normal distribution. In the case of z-score or t-statistic, it is 0 at the mean of the sample due to its mathematical definition.</p>
</div>
<div id="question-6-3" class="section level3">
<h3><span class="header-section-number">3.4.6</span> Question 6</h3>
<div class="question">
<p>The result of 4 and 5 tell us that we know the distribution of the difference between our estimate and what we want to estimate, but don’t know. However, the equation involves the population standard deviation <span class="math inline">\(\sigma_X\)</span>, which we don’t know. Given what we discussed, what is your estimate of <span class="math inline">\(\sigma_x\)</span>?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1"><span class="kw">sd</span>(X)</a></code></pre></div>
<pre><code>## [1] 3.022541</code></pre>
</div>
<div id="question-7-3" class="section level3">
<h3><span class="header-section-number">3.4.7</span> Question 7</h3>
<div class="question">
<p>Use the CLT to approximate the probability that our estimate <span class="math inline">\(\bar{X}\)</span> is off by more than 2 grams from <span class="math inline">\(\mu_x\)</span>.</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1">z_score &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">/</span>(<span class="kw">sqrt</span>(<span class="kw">sd</span>(X)<span class="op">^</span><span class="dv">2</span><span class="op">/</span><span class="dv">12</span>))</a>
<a class="sourceLine" id="cb96-2" title="2"><span class="kw">pnorm</span>(<span class="op">-</span>z_score) <span class="op">+</span><span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(z_score)</a></code></pre></div>
<pre><code>## [1] 0.02189533</code></pre>
</div>
<div id="question-8-3" class="section level3">
<h3><span class="header-section-number">3.4.8</span> Question 8</h3>
<div class="question">
<p>Now we introduce the concept of a null hypothesis. We don’t know <span class="math inline">\(\mu_x\)</span> nor <span class="math inline">\(mu_y\)</span>. We want to quantify what the data say about the possibility that the diet has
no effect: <span class="math inline">\(\mu_x = \mu_y\)</span>. If we use CLT, then we approximate the distribution of <span class="math inline">\(\bar{X}\)</span> as normal with mean <span class="math inline">\(mu_X\)</span> and standard deviation of <span class="math inline">\(\frac{\sigma_X}{\sqrt{M}}\)</span> and the distribution of <span class="math inline">\(\bar{Y}\)</span> and standard deviation of <span class="math inline">\(\frac{\sigma_y}{\sqrt{N}}\)</span>, with <span class="math inline">\(M\)</span> and <span class="math inline">\(N\)</span> as the sample sizes for <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> respectively, in this case 12. This implies that the difference <span class="math inline">\(\bar{Y} - \bar{X}\)</span> has mean <span class="math inline">\(0\)</span>. We described that the standard deviation of this statistic (the standard error) is <span class="math inline">\(SE(\bar{Y} - \bar{X}) = \sqrt{\sigma_y^2/12 + \sigma_x^2/12}\)</span> and that we estimate the population standard deviations <span class="math inline">\(\sigma_x\)</span> and <span class="math inline">\(\sigma_y\)</span> with the sample estimates. What is the estimate of <span class="math inline">\(SE(\bar{Y} - \bar{X}) = \sqrt{\sigma_y^2/12 + \sigma_x^2/12}\)</span>?</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1"><span class="kw">sqrt</span>((<span class="kw">sd</span>(X)<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">sd</span>(Y)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="dv">12</span>)</a></code></pre></div>
<pre><code>## [1] 1.469867</code></pre>
</div>
<div id="question-9-3" class="section level3">
<h3><span class="header-section-number">3.4.9</span> Question 9</h3>
<div class="question">
<p>So now we can compute <span class="math inline">\(\bar{Y}-\bar{X}\)</span> as well as an estimate of this standard error and construct a t-statistic. What is this t-statistic?</p>
</div>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" title="1">(<span class="kw">mean</span>(Y) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(X))<span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>((<span class="kw">sd</span>(X)<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">sd</span>(Y)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="dv">12</span>)</a></code></pre></div>
<pre><code>## [1] 2.055174</code></pre>
<p>This is a good formula to memorize because it will return in later chapters. Knowing this formula can enable us to compute p-values from scratch.</p>
</div>
<div id="question-10-2" class="section level3">
<h3><span class="header-section-number">3.4.10</span> Question 10</h3>
<div class="question">
<p>If we apply the CLT, what is the distribution of this t-statistic?</p>
</div>
<div class="answer">

<p>The answer is <strong>A: Normal with mean 0 and standard deviation 1</strong>.</p>
<p>T-statistic is z-score, so the values are standardized to the sample mean. Therefore, the mean is 0.</p>
</div>
<div id="question-11-1" class="section level3">
<h3><span class="header-section-number">3.4.11</span> Question 11</h3>
<div class="question">
<p>Now we are ready to compute a p-value using the CLT. What is the probability of observing a quantity as large as what we computed for <strong>t-statistic in Question 9</strong>, when the null distribution is true?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1">tstat &lt;-<span class="st"> </span>(<span class="kw">mean</span>(Y) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(X))<span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>((<span class="kw">sd</span>(X)<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">sd</span>(Y)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="dv">12</span>) <span class="co"># from question 9</span></a>
<a class="sourceLine" id="cb102-2" title="2"><span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(tstat))</a></code></pre></div>
<pre><code>## [1] 0.0398622</code></pre>
</div>
<div id="question-12-1" class="section level3">
<h3><span class="header-section-number">3.4.12</span> Question 12</h3>
<div class="question">
<p>CLT provides an approximation for cases in which the sample size is large. In practice, we can’t check the assumption because we only get to see 1 outcome (which you computed above). As a result, if this approximation is off, so is our p-value. As described earlier, there is another approach that does not require a large sample size, but rather that the distribution of the population is approximately normal. We don’t get to see this distribution so it is again an assumption, although we can look at the distribution of the sample with <code>qqnorm(X)</code> and <code>qqnorm(Y)</code>. If we are willing to assume this, then it follows that the t-statistic follows t-
distribution. What is the p-value under the t-distribution approximation? Hint: use the <code>t.test</code> function.</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1"><span class="kw">mypar</span>(<span class="dv">1</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb104-2" title="2"><span class="kw">qqnorm</span>(X, <span class="dt">main =</span> <span class="st">&#39;Theoretical normal quantiles vs X&#39;</span>)</a>
<a class="sourceLine" id="cb104-3" title="3"><span class="kw">qqline</span>(X)</a>
<a class="sourceLine" id="cb104-4" title="4"><span class="kw">qqnorm</span>(Y, <span class="dt">main =</span> <span class="st">&#39;Theoretical normal quantiles vs Y&#39;</span>)</a>
<a class="sourceLine" id="cb104-5" title="5"><span class="kw">qqline</span>(Y)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" title="1"><span class="kw">t.test</span>(X,Y)<span class="op">$</span>p.value</a></code></pre></div>
<pre><code>## [1] 0.05299888</code></pre>
</div>
<div id="question-13-1" class="section level3">
<h3><span class="header-section-number">3.4.13</span> Question 13</h3>
<div class="question">
<p>With the CLT distribution, we obtained a p-value smaller than 0.05 and with the t-distribution, one that is larger. They can’t both be right. What best describes the difference?</p>
</div>
<div class="answer">

<p>The answer is <strong>B: These are two different assumptions. The t-distribution accounts for the variability introduced by the estimation of the standard error and thus, under the null, large values are more probable under the null distribution.</strong></p>
</div>
</div>
<div id="ch-2.18-exercises" class="section level2">
<h2><span class="header-section-number">3.5</span> Ch 2.18 Exercises</h2>
<p>For these exercises we will load the babies dataset from <code>babies.txt</code>. We will use this data to review the concepts behind the p-values and then test confidence interval concepts.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" title="1">babies &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;babies.txt&quot;</span>, <span class="dt">header=</span><span class="ot">TRUE</span>)</a></code></pre></div>
<p>This is a large dataset (1,236 cases), and we will pretend that it contains the entire population in which we are interested. We will study the differences in birth weight between babies born to smoking and non-smoking mothers.
First, let’s split this into two birth weight datasets: one of birth weights to non-smoking mothers and the other of birth weights to smoking mothers.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" title="1">bwt.nonsmoke &lt;-<span class="st"> </span><span class="kw">filter</span>(babies, smoke<span class="op">==</span><span class="dv">0</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(bwt) <span class="op">%&gt;%</span><span class="st"> </span>unlist</a>
<a class="sourceLine" id="cb108-2" title="2">bwt.smoke &lt;-<span class="st"> </span><span class="kw">filter</span>(babies, smoke<span class="op">==</span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(bwt) <span class="op">%&gt;%</span><span class="st"> </span>unlist</a></code></pre></div>
<p>Now, we can look for the true population difference in means between smoking and non-smoking birth weights.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" title="1"><span class="kw">library</span>(rafalib)</a>
<a class="sourceLine" id="cb109-2" title="2"><span class="kw">mean</span>(bwt.nonsmoke)<span class="op">-</span><span class="kw">mean</span>(bwt.smoke)</a></code></pre></div>
<pre><code>## [1] 8.937666</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" title="1"><span class="kw">popsd</span>(bwt.nonsmoke)</a></code></pre></div>
<pre><code>## [1] 17.38696</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1"><span class="kw">popsd</span>(bwt.smoke)</a></code></pre></div>
<pre><code>## [1] 18.08024</code></pre>
<p>The population difference of mean birth weights is about 8.9 ounces. The standard deviations of the nonsmoking and smoking groups are about 17.4 and 18.1 ounces, respectively.</p>
<p>As we did with the mouse weight data, this assessment interactively reviews inference concepts using simulations in R. We will treat the babies dataset as the full population
and draw samples from it to simulate individual experiments. We will then ask whether somebody who only received the random samples would be able to draw correct conclusions
about the population.</p>
<p>We are interested in testing whether the birth weights of babies born to non-smoking mothers are significantly different from the birth weights of babies born to smoking mothers.</p>
<div id="question-1-5" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Question 1</h3>
<div class="question">
<p>Set the seed at 1 and obtain two samples, each of size N = 25, from non-smoking mothers (dat.ns) and smoking mothers (dat.s). Compute the t-statistic (call it tval).</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" title="1">N &lt;-<span class="st"> </span><span class="dv">25</span></a>
<a class="sourceLine" id="cb115-2" title="2"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb115-3" title="3">dat.ns &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.nonsmoke,N)</a>
<a class="sourceLine" id="cb115-4" title="4">dat.s &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.smoke,N)</a>
<a class="sourceLine" id="cb115-5" title="5">tval &lt;-<span class="st"> </span>(<span class="kw">mean</span>(dat.s) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(dat.ns)) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">var</span>(dat.s)<span class="op">/</span>N <span class="op">+</span><span class="st"> </span><span class="kw">var</span>(dat.ns)<span class="op">/</span>N)</a>
<a class="sourceLine" id="cb115-6" title="6"><span class="kw">t.test</span>(dat.s,dat.ns)<span class="op">$</span>statistic[[<span class="dv">1</span>]]</a></code></pre></div>
<pre><code>## [1] -2.120904</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1"><span class="kw">pt</span>(tval, <span class="dt">df =</span> N<span class="op">*</span><span class="dv">2-2</span>)<span class="op">*</span><span class="dv">2</span></a></code></pre></div>
<pre><code>## [1] 0.03912225</code></pre>
</div>
<div id="question-2-4" class="section level3">
<h3><span class="header-section-number">3.5.2</span> Question 2</h3>
<div class="question">
<p>Recall that we summarize our data using a t-statistics because we know that in situations where the null hypothesis is true (what we mean when we say “under the null”) and the sample size is relatively large, this t-value will have an approximate standard normal distribution. Because we know the distribution of the t-value under the null, we can quantitatively determine how unusual the observed t-value would be if the null hypothesis were true.</p>
<p>The standard procedure is to examine the probability a t-statistic that actually does follow the null hypothesis would have larger absolute value than the absolute value of the t-value we just observed- this is called a two-sided test.</p>
<p>We have computed these by taking one minus the area under the standard normal curve between <code>-abs(tval)</code> and <code>abs(tval)</code>. In R, we can do this by using the pnorm function, which computes the area under a normal curve from negative infinity up to the value given as its first argument. <strong>What is the estimated p-value?</strong></p>
</div>
<div class="answer">


<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" title="1">(<span class="kw">pnorm</span>(tval) <span class="op">+</span><span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span>tval))</a></code></pre></div>
<pre><code>## [1] 0.03392985</code></pre>
</div>
<div id="question-3-4" class="section level3">
<h3><span class="header-section-number">3.5.3</span> Question 3</h3>
<div class="question">
<p>Because of the symmetry of the standard normal distribution, there is a simpler way to calculate the probability that a t-value under the null could have a larger absolute value than <code>tval</code>. <strong>Choose a simplified calculation from the four choices.</strong></p>
</div>
<div class="answer">


<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb121-1" title="1"><span class="dv">2</span><span class="op">*</span><span class="kw">pnorm</span>(<span class="op">-</span><span class="kw">abs</span>(tval))</a></code></pre></div>
<pre><code>## [1] 0.03392985</code></pre>
</div>
<div id="question-4-4" class="section level3">
<h3><span class="header-section-number">3.5.4</span> Question 4</h3>
<div class="question">
<p>By reporting only p-values, many scientific publications provide an incomplete story of their findings. As we have mentioned, with very large sample sizes, scientifically insignificant differences between two groups can lead to small p-values. Confidence intervals are more informative as they include the estimate itself. Our estimate of the difference between babies of smokers and non-smokers: <code>mean(dat.s) - mean( dat.ns)</code>. If we use the CLT, what quantity would we add and subtract to this estimate to obtain a 99% confidence interval?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb123-1" title="1"><span class="kw">mean</span>(dat.s) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(dat.ns)</a></code></pre></div>
<pre><code>## [1] -9.92</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" title="1">Q &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.5</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.99</span><span class="op">/</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb125-2" title="2">se &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">var</span>(dat.ns)<span class="op">/</span>N <span class="op">+</span><span class="st"> </span><span class="kw">var</span>(dat.s)<span class="op">/</span>N)</a>
<a class="sourceLine" id="cb125-3" title="3"><span class="kw">c</span>(<span class="op">-</span>Q<span class="op">*</span>se <span class="op">+</span><span class="st"> </span><span class="kw">mean</span>(dat.s) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(dat.ns), <span class="kw">mean</span>(dat.s) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(dat.ns) <span class="op">+</span><span class="st"> </span>Q<span class="op">*</span>se)</a></code></pre></div>
<pre><code>## [1] -21.967797   2.127797</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" title="1"><span class="kw">print</span>(Q<span class="op">*</span>se)</a></code></pre></div>
<pre><code>## [1] 12.0478</code></pre>
</div>
<div id="question-5-4" class="section level3">
<h3><span class="header-section-number">3.5.5</span> Question 5</h3>
<div class="question">
<p>If instead of CLT, we use the t-distribution approximation, what do we add and subtract (use <code>2*N-2</code> degrees of freedom)?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb129-1" title="1">Qt &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.5</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.99</span><span class="op">/</span><span class="dv">2</span>, <span class="dt">df =</span> N<span class="op">*</span><span class="dv">2-2</span>)</a>
<a class="sourceLine" id="cb129-2" title="2">se &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">var</span>(dat.ns)<span class="op">/</span>N <span class="op">+</span><span class="st"> </span><span class="kw">var</span>(dat.s)<span class="op">/</span>N)</a>
<a class="sourceLine" id="cb129-3" title="3"><span class="kw">c</span>(<span class="op">-</span>Qt<span class="op">*</span>se <span class="op">+</span><span class="st"> </span><span class="kw">mean</span>(dat.s) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(dat.ns), <span class="kw">mean</span>(dat.s) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(dat.ns) <span class="op">+</span><span class="st"> </span>Qt<span class="op">*</span>se)</a></code></pre></div>
<pre><code>## [1] -22.465339   2.625339</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" title="1"><span class="kw">t.test</span>(dat.s, dat.ns)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  dat.s and dat.ns
## t = -2.1209, df = 47.693, p-value = 0.03916
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -19.3258047  -0.5141953
## sample estimates:
## mean of x mean of y 
##    114.76    124.68</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" title="1"><span class="kw">print</span>(Qt<span class="op">*</span>se)</a></code></pre></div>
<pre><code>## [1] 12.54534</code></pre>
</div>
<div id="question-6-4" class="section level3">
<h3><span class="header-section-number">3.5.6</span> Question 6</h3>
<div class="question">
<p>Why are the values from 4 and 5 so similar?</p>
</div>
<div class="answer">

<p>The answer is <strong>C: <code>N</code> and thus the degrees of freedom is large enough to make the normal and t-distributions very similar.</strong></p>
</div>
<div id="question-7-4" class="section level3">
<h3><span class="header-section-number">3.5.7</span> Question 7</h3>
<div class="question">
<p>Which of the following sentences about a Type I error is <strong>false</strong>?</p>
</div>
<div class="answer">

The answer is <strong>C: From the original data alone, you can tell whether you have made a Type I error.</strong>
<div class="answer">

</div>
<div id="question-8-4" class="section level3">
<h3><span class="header-section-number">3.5.8</span> Question 8</h3>
<div class="question">
<p>Set the seed at 1 and take a random sample of <span class="math inline">\(N = 5\)</span> measurements from each of the smoking and nonsmoking datasets. What is the p-value (use the <code>t-test</code> function)?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" title="1">N &lt;-<span class="st"> </span><span class="dv">5</span></a>
<a class="sourceLine" id="cb135-2" title="2"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb135-3" title="3">ns_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.nonsmoke, N)</a>
<a class="sourceLine" id="cb135-4" title="4">s_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.smoke, N)</a>
<a class="sourceLine" id="cb135-5" title="5"><span class="kw">t.test</span>(ns_sample, s_sample)<span class="op">$</span>p.value</a></code></pre></div>
<pre><code>## [1] 0.1366428</code></pre>
</div>
<div id="question-9-4" class="section level3">
<h3><span class="header-section-number">3.5.9</span> Question 9</h3>
<div class="question">
<p>The p-value is larger than 0.05 so using the typical cut-off, we would not reject. This is a type II error <strong>(false negative)</strong>. Which of the following is not a way to decrease this type of error?</p>
</div>
<div class="answer">

<p>The answer is <strong>C: Find a population for which the null is not true.</strong></p>
</div>
<div id="question-10-3" class="section level3">
<h3><span class="header-section-number">3.5.10</span> Question 10</h3>
<div class="question">
<p>Set the seed at 1, then use the <code>replicate</code> function to repeat the code in Exercise 9 10,000 times. What proportion of the time do we reject at the 0.05 level?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" title="1">B &lt;-<span class="st"> </span><span class="dv">10000</span></a>
<a class="sourceLine" id="cb137-2" title="2">alpha &lt;-<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb137-3" title="3"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb137-4" title="4">N &lt;-<span class="st"> </span><span class="dv">5</span></a>
<a class="sourceLine" id="cb137-5" title="5">res_list&lt;-<span class="st"> </span><span class="kw">replicate</span>(B, {</a>
<a class="sourceLine" id="cb137-6" title="6">  ns_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.nonsmoke, N)</a>
<a class="sourceLine" id="cb137-7" title="7">  s_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.smoke, N)</a>
<a class="sourceLine" id="cb137-8" title="8">  pval &lt;-<span class="st"> </span><span class="kw">t.test</span>(ns_sample, s_sample)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb137-9" title="9">  <span class="kw">return</span>(alpha <span class="op">&gt;</span><span class="st"> </span>pval) <span class="co"># this returns logical (i.e., TRUE if pval is smaller than 0.05 = alpha), and stores in the vector res_list.</span></a>
<a class="sourceLine" id="cb137-10" title="10">})</a>
<a class="sourceLine" id="cb137-11" title="11"><span class="kw">mean</span>(res_list) </a></code></pre></div>
<pre><code>## [1] 0.0984</code></pre>
</div>
<div id="question-11-2" class="section level3">
<h3><span class="header-section-number">3.5.11</span> Question 11</h3>
<div class="question">
<p>Note that, not surprisingly, the power is lower than 10%. Repeat the exercise above for sample sizes of 30, 60, 90 and 120. Which of these four gives you power of about 80%?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1">pval_calc &lt;-<span class="st"> </span><span class="cf">function</span>(N) {</a>
<a class="sourceLine" id="cb139-2" title="2">  ns_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.nonsmoke, N)</a>
<a class="sourceLine" id="cb139-3" title="3">  s_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.smoke, N)</a>
<a class="sourceLine" id="cb139-4" title="4">  pval &lt;-<span class="st"> </span><span class="kw">t.test</span>(ns_sample, s_sample)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb139-5" title="5">  <span class="kw">return</span>(pval)</a>
<a class="sourceLine" id="cb139-6" title="6">}</a>
<a class="sourceLine" id="cb139-7" title="7"></a>
<a class="sourceLine" id="cb139-8" title="8">Ns &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>,<span class="dv">60</span>,<span class="dv">90</span>,<span class="dv">120</span>)</a>
<a class="sourceLine" id="cb139-9" title="9">B &lt;-<span class="st"> </span><span class="dv">10000</span></a>
<a class="sourceLine" id="cb139-10" title="10">alpha &lt;-<span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb139-11" title="11">res_list &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&#39;double&#39;</span>,<span class="kw">length</span>(Ns))</a>
<a class="sourceLine" id="cb139-12" title="12"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(Ns)) {</a>
<a class="sourceLine" id="cb139-13" title="13">  res_list[[i]] &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">replicate</span>(B, <span class="kw">pval_calc</span>(Ns[[i]])) <span class="op">&lt;</span><span class="st"> </span>alpha)</a>
<a class="sourceLine" id="cb139-14" title="14">}</a>
<a class="sourceLine" id="cb139-15" title="15"><span class="kw">names</span>(res_list) &lt;-<span class="st"> </span>Ns</a>
<a class="sourceLine" id="cb139-16" title="16"><span class="kw">print</span>(res_list) <span class="co"># sample size of 60 gives power of 80%</span></a></code></pre></div>
<pre><code>##     30     60     90    120 
## 0.4933 0.7868 0.9344 0.9835</code></pre>
<p>Sample size of 60 gives power of 80%.</p>
</div>
<div id="question-12-2" class="section level3">
<h3><span class="header-section-number">3.5.12</span> Question 12</h3>
<div class="question">
<p>Repeat <strong>Question 11</strong>, but now require an <span class="math inline">\(\alpha\)</span> level of 0.01. Which of these four gives you power of 80%?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" title="1">pval_calc &lt;-<span class="st"> </span><span class="cf">function</span>(N) {</a>
<a class="sourceLine" id="cb141-2" title="2">  ns_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.nonsmoke, N)</a>
<a class="sourceLine" id="cb141-3" title="3">  s_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.smoke, N)</a>
<a class="sourceLine" id="cb141-4" title="4">  pval &lt;-<span class="st"> </span><span class="kw">t.test</span>(ns_sample, s_sample)<span class="op">$</span>p.value</a>
<a class="sourceLine" id="cb141-5" title="5">  <span class="kw">return</span>(pval)</a>
<a class="sourceLine" id="cb141-6" title="6">}</a>
<a class="sourceLine" id="cb141-7" title="7"></a>
<a class="sourceLine" id="cb141-8" title="8">Ns &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>,<span class="dv">60</span>,<span class="dv">90</span>,<span class="dv">120</span>)</a>
<a class="sourceLine" id="cb141-9" title="9">B &lt;-<span class="st"> </span><span class="dv">10000</span></a>
<a class="sourceLine" id="cb141-10" title="10">alpha &lt;-<span class="st"> </span><span class="fl">0.01</span></a>
<a class="sourceLine" id="cb141-11" title="11">res_list &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&#39;double&#39;</span>,<span class="kw">length</span>(Ns))</a>
<a class="sourceLine" id="cb141-12" title="12"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(Ns)) {</a>
<a class="sourceLine" id="cb141-13" title="13">  res_list[[i]] &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">replicate</span>(B, <span class="kw">pval_calc</span>(Ns[[i]])) <span class="op">&lt;</span><span class="st"> </span>alpha)</a>
<a class="sourceLine" id="cb141-14" title="14">}</a>
<a class="sourceLine" id="cb141-15" title="15"><span class="kw">names</span>(res_list) &lt;-<span class="st"> </span>Ns</a>
<a class="sourceLine" id="cb141-16" title="16"><span class="kw">print</span>(res_list) <span class="co"># sample size of 90 gives power of 80%</span></a></code></pre></div>
<pre><code>##     30     60     90    120 
## 0.2461 0.5607 0.7932 0.9241</code></pre>
<p>Sample size of 90 gives power of 80%.</p>
</div>
</div>
<div id="ch-2.21-exercises" class="section level2">
<h2><span class="header-section-number">3.6</span> Ch 2.21 Exercises</h2>
<p>We have used Monte Carlo simulation throughout this chapter to demonstrate statistical concepts; namely, sampling from the population. We mostly applied this to demonstrate the
statistical properties related to inference on differences in averages. Here, we will consider examples of how Monte Carlo simulations are used in practice.</p>
<div id="question-1-6" class="section level3">
<h3><span class="header-section-number">3.6.1</span> Question 1</h3>
<div class="question">
<p>Imagine you are William Sealy Gosset and have just mathematically derived the distribution of the t-statistic when the sample comes from a normal distribution. Unlike Gosset you have access to computers and can use them to check the results.</p>
<p>Let’s start by creating an outcome. Set the seed at 1, use <code>rnorm</code> to generate a random sample of size 5, <span class="math inline">\(X_1,...,.X_5\)</span> from a standard normal distribution, then compute the t-statistic <span class="math inline">\(t = \sqrt{5}\bar{X}/s\)</span> with <span class="math inline">\(s\)</span> the sample standard deviation. What value do you observe?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb143-2" title="2">n &lt;-<span class="st"> </span><span class="dv">5</span></a>
<a class="sourceLine" id="cb143-3" title="3">sample1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n)</a>
<a class="sourceLine" id="cb143-4" title="4">tstat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">5</span>)<span class="op">*</span><span class="kw">mean</span>(sample1)<span class="op">/</span><span class="kw">sd</span>(sample1)</a>
<a class="sourceLine" id="cb143-5" title="5">tstat</a></code></pre></div>
<pre><code>## [1] 0.3007746</code></pre>
</div>
<div id="question-2-5" class="section level3">
<h3><span class="header-section-number">3.6.2</span> Question 2</h3>
<div class="question">
<p>You have just performed a Monte Carlo simulation using rnorm, a random number generator for normally distributed data. Gosset’s mathematical calculation tells us that the t-statistic defined in the previous exercise, a random variable, follows a t-distribution with <span class="math inline">\(N-1\)</span> degrees of freedom. Monte Carlo simulations can be used to check the theory: we generate many outcomes and compare them to the
theoretical result. Set the seed to 1, generate B = 1000 t-statistics as done in <strong>Question 1</strong>. What proportion is larger than 2?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb145-2" title="2">samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">5</span>)</a>
<a class="sourceLine" id="cb145-3" title="3">tstat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">5</span>)<span class="op">*</span>samp<span class="op">/</span><span class="kw">sd</span>(samp)</a>
<a class="sourceLine" id="cb145-4" title="4"></a>
<a class="sourceLine" id="cb145-5" title="5">get_t &lt;-<span class="st"> </span><span class="cf">function</span>(n) {</a>
<a class="sourceLine" id="cb145-6" title="6">  samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n)</a>
<a class="sourceLine" id="cb145-7" title="7">  tstat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(n)<span class="op">*</span><span class="kw">mean</span>(samp)<span class="op">/</span><span class="kw">sd</span>(samp)</a>
<a class="sourceLine" id="cb145-8" title="8">  <span class="kw">return</span>(tstat)</a>
<a class="sourceLine" id="cb145-9" title="9">}</a>
<a class="sourceLine" id="cb145-10" title="10"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb145-11" title="11">res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">get_t</span>(<span class="dv">5</span>))</a>
<a class="sourceLine" id="cb145-12" title="12"><span class="kw">mean</span>(res_list <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 0.068</code></pre>
</div>
<div id="question-3-5" class="section level3">
<h3><span class="header-section-number">3.6.3</span> Question 3</h3>
<div class="question">
<p>The answer to <strong>Question 2</strong> is very similar to the theoretical prediction: <code>1-pt(2,df=4)</code>. We can check several such quantiles using <code>qqplot</code> function.</p>
<p>To obtain quantiles for the t-distribution we can generate percentiles from just above 0 to just below <code>1: B=100; ps = seq(1/(B+1), 1-1/(B+1), len = B)</code> and compute the quantiles with <code>qt(ps, df=4)</code>. Now we can use <code>qqplot</code> to compare these theoretical quantiles to those obtained in Monte Carlo simulation. Use Monte Carlo simulation developed for <strong>Question 2</strong> to corroborate that the t-statistic <span class="math inline">\(t = \sqrt{N}\bar{X}/s\)</span> follows a t-distribution for several values of N.</p>
<p>For which sample sizes does the approximation best work?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" title="1">B &lt;-<span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb147-2" title="2">ps =<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span><span class="op">/</span>(B<span class="op">+</span><span class="dv">1</span>), <span class="dv">1-1</span><span class="op">/</span>(B<span class="op">+</span><span class="dv">1</span>),<span class="dt">len=</span>B)</a>
<a class="sourceLine" id="cb147-3" title="3"></a>
<a class="sourceLine" id="cb147-4" title="4">get_t &lt;-<span class="st"> </span><span class="cf">function</span>(n) {</a>
<a class="sourceLine" id="cb147-5" title="5">  samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n)</a>
<a class="sourceLine" id="cb147-6" title="6">  tstat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(n)<span class="op">*</span><span class="kw">mean</span>(samp)<span class="op">/</span><span class="kw">sd</span>(samp)</a>
<a class="sourceLine" id="cb147-7" title="7">  <span class="kw">return</span>(tstat)</a>
<a class="sourceLine" id="cb147-8" title="8">}</a>
<a class="sourceLine" id="cb147-9" title="9"></a>
<a class="sourceLine" id="cb147-10" title="10">Ns &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">100</span>)</a>
<a class="sourceLine" id="cb147-11" title="11"><span class="kw">mypar</span>(<span class="dv">2</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb147-12" title="12"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb147-13" title="13"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(Ns)) {</a>
<a class="sourceLine" id="cb147-14" title="14">  res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">get_t</span>(Ns[i]))</a>
<a class="sourceLine" id="cb147-15" title="15">  theory_t &lt;-<span class="st"> </span><span class="kw">qt</span>(ps,<span class="dt">df=</span>Ns[i]<span class="op">-</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb147-16" title="16">  <span class="kw">qqplot</span>(theory_t, res_list, <span class="dt">main =</span> <span class="kw">paste0</span>(<span class="st">&#39;sample size= &#39;</span>,Ns[i]),</a>
<a class="sourceLine" id="cb147-17" title="17">         <span class="dt">xlab =</span> <span class="st">&#39;theory&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;sim&#39;</span>)</a>
<a class="sourceLine" id="cb147-18" title="18">  <span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb147-19" title="19">}</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>The approximations are spot on for all sample sizes (<strong>answer choice C</strong>).</p>
</div>
<div id="question-4-5" class="section level3">
<h3><span class="header-section-number">3.6.4</span> Question 4</h3>
<div class="question">
<p>Use Monte Carlo simulation to corroborate that the t-statistic comparing two means and obtained with normally distributed (mean 0 and sd) data follows a t-distribution. In this case we will use the <code>t.test</code> function with <code>var.equal=TRUE</code>. With this argument the degrees of freedom will be <code>df=2*N-2</code> with <code>N</code> the sample size. For which sample sizes does the approximation best work?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1">ttestgenerator &lt;-<span class="st"> </span><span class="cf">function</span>(n) {</a>
<a class="sourceLine" id="cb148-2" title="2">  cases &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n)</a>
<a class="sourceLine" id="cb148-3" title="3">  controls &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n)</a>
<a class="sourceLine" id="cb148-4" title="4">  tstat &lt;-<span class="st"> </span><span class="kw">t.test</span>(cases,controls)<span class="op">$</span>statistic[[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb148-5" title="5">  <span class="kw">return</span>(tstat)</a>
<a class="sourceLine" id="cb148-6" title="6">}</a>
<a class="sourceLine" id="cb148-7" title="7"></a>
<a class="sourceLine" id="cb148-8" title="8">Ns &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">100</span>)</a>
<a class="sourceLine" id="cb148-9" title="9"><span class="kw">mypar</span>(<span class="dv">2</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb148-10" title="10"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb148-11" title="11"><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(Ns)) {</a>
<a class="sourceLine" id="cb148-12" title="12">  res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">ttestgenerator</span>(Ns[i]))</a>
<a class="sourceLine" id="cb148-13" title="13">  theory_t &lt;-<span class="st"> </span><span class="kw">qt</span>(ps,<span class="dt">df=</span><span class="dv">2</span><span class="op">*</span>Ns[i]<span class="op">-</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb148-14" title="14">  <span class="kw">qqplot</span>(theory_t, res_list, <span class="dt">main =</span> <span class="kw">paste0</span>(<span class="st">&#39;sample size= &#39;</span>,Ns[i]),</a>
<a class="sourceLine" id="cb148-15" title="15">         <span class="dt">xlab =</span> <span class="st">&#39;theory&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;sim&#39;</span>)</a>
<a class="sourceLine" id="cb148-16" title="16">  <span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb148-17" title="17">}</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>The approximations are spot on for all sample sizes (<strong>answer choice C</strong>).</p>
</div>
<div id="question-5-5" class="section level3">
<h3><span class="header-section-number">3.6.5</span> Question 5</h3>
<div class="question">
<p>Is the following statement true or false? If instead of generating the sample with <code>X = rnorm(15)</code>, we generate it with binary data (either positive or negative 1 with probability 0.5) <code>X = sample(c(-1,1),15,replace = TRUE)</code> then the t-statistic
<code>tstat &lt;- sqrt(15) * mean(X) / sd(X)</code>
is approximated by a t-distribution with 14 degrees of freedom.</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb149-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb149-2" title="2">res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, {</a>
<a class="sourceLine" id="cb149-3" title="3">  X &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dv">15</span>,<span class="dt">replace =</span> T)</a>
<a class="sourceLine" id="cb149-4" title="4">  tstat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">15</span>) <span class="op">*</span><span class="st"> </span><span class="kw">mean</span>(X)<span class="op">/</span><span class="kw">sd</span>(X)</a>
<a class="sourceLine" id="cb149-5" title="5">  <span class="kw">return</span>(tstat)</a>
<a class="sourceLine" id="cb149-6" title="6">})</a>
<a class="sourceLine" id="cb149-7" title="7"></a>
<a class="sourceLine" id="cb149-8" title="8">ps &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span><span class="op">/</span>(B<span class="op">+</span><span class="dv">1</span>), <span class="dv">1-1</span><span class="op">/</span>(B<span class="op">+</span><span class="dv">1</span>),<span class="dt">len=</span>B)</a>
<a class="sourceLine" id="cb149-9" title="9">theory_t &lt;-<span class="st"> </span><span class="kw">qt</span>(ps,<span class="dt">df=</span><span class="dv">14</span>)</a>
<a class="sourceLine" id="cb149-10" title="10"><span class="kw">qqplot</span>(res_list, theory_t)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-76-1.png" width="672" /></p>
<p><strong>False</strong>. Instead, it is approximated by binomial distribution because the data are binary (only two values).</p>
</div>
<div id="question-6-5" class="section level3">
<h3><span class="header-section-number">3.6.6</span> Question 6</h3>
<div class="question">
<p>Is the following statement true or false? If instead of generating the sample with <code>X = rnorm(N)</code> with <code>N = 1000</code>, we generate it with binary data <code>X = sample(c(-1,1),15,replace = TRUE)</code> then the t-statistic
<code>tstat &lt;- sqrt(15) * mean(X) / sd(X)</code>
is approximated by a t-distribution with 999 degrees of freedom.</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb150-2" title="2">res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, {</a>
<a class="sourceLine" id="cb150-3" title="3">  X &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dv">1000</span>,<span class="dt">replace =</span> T)</a>
<a class="sourceLine" id="cb150-4" title="4">  tstat &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">1000</span>) <span class="op">*</span><span class="st"> </span><span class="kw">mean</span>(X)<span class="op">/</span><span class="kw">sd</span>(X)</a>
<a class="sourceLine" id="cb150-5" title="5">  <span class="kw">return</span>(tstat)</a>
<a class="sourceLine" id="cb150-6" title="6">})</a>
<a class="sourceLine" id="cb150-7" title="7">B&lt;-<span class="dv">1000</span></a>
<a class="sourceLine" id="cb150-8" title="8">ps &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span><span class="op">/</span>(B<span class="op">+</span><span class="dv">1</span>), <span class="dv">1-1</span><span class="op">/</span>(B<span class="op">+</span><span class="dv">1</span>),<span class="dt">len=</span>B)</a>
<a class="sourceLine" id="cb150-9" title="9">theory_t &lt;-<span class="st"> </span><span class="kw">qt</span>(ps,<span class="dt">df=</span><span class="dv">999</span>)</a>
<a class="sourceLine" id="cb150-10" title="10"><span class="kw">qqplot</span>(res_list, theory_t)</a>
<a class="sourceLine" id="cb150-11" title="11"><span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</a></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-77-1.png" width="672" />
<strong>True</strong>.</p>
</div>
<div id="question-7-5" class="section level3">
<h3><span class="header-section-number">3.6.7</span> Question 7</h3>
<div class="question">
<p>We can derive approximation of the distribution of the sample average or the t-statistic theoretically. However, suppose we are interested in the distribution of a statistic for which a theoretical approximation is not immediately obvious.</p>
<p>Consider the sample median as an example. Use a Monte Carlo to determine which of the following best approximates the median of a sample taken from normally distributed population with mean 0 and standard deviation 1.</p>
</div>
<div class="answer">

<p>The answer is <strong>A: Just like for the average, the sample median is approximately normal with mean 0 and SD <span class="math inline">\(1/\sqrt{N}\)</span>.</strong></p>
</div>
</div>
<div id="ch-2.23-exercises" class="section level2">
<h2><span class="header-section-number">3.7</span> Ch 2.23 Exercises</h2>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" title="1">babies &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;babies.txt&quot;</span>, <span class="dt">header=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb151-2" title="2">bwt.nonsmoke &lt;-<span class="st"> </span><span class="kw">filter</span>(babies, smoke<span class="op">==</span><span class="dv">0</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(bwt) <span class="op">%&gt;%</span><span class="st"> </span>unlist</a>
<a class="sourceLine" id="cb151-3" title="3">bwt.smoke &lt;-<span class="st"> </span><span class="kw">filter</span>(babies, smoke<span class="op">==</span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(bwt) <span class="op">%&gt;%</span><span class="st"> </span>unlist</a></code></pre></div>
<div id="question-1-7" class="section level3">
<h3><span class="header-section-number">3.7.1</span> Question 1</h3>
<div class="question">
<p>We will generate the following random variable based on a sample size of 10 and observe the following difference:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1">N=<span class="dv">10</span></a>
<a class="sourceLine" id="cb152-2" title="2"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb152-3" title="3">nonsmokers &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.nonsmoke , N)</a>
<a class="sourceLine" id="cb152-4" title="4">smokers &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.smoke , N)</a>
<a class="sourceLine" id="cb152-5" title="5">obs &lt;-<span class="st"> </span><span class="kw">mean</span>(smokers) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(nonsmokers)</a></code></pre></div>
<p>The question is whether this observed difference is statistically significant. We do not want to rely on the assumptions needed for the normal or t-distribution approximations to hold, so instead we will use permutations. We will reshuffle the data and recompute the mean. We can create one permuted sample with the following code:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" title="1">dat &lt;-<span class="st"> </span><span class="kw">c</span>(smokers,nonsmokers)</a>
<a class="sourceLine" id="cb153-2" title="2">shuffle &lt;-<span class="st"> </span><span class="kw">sample</span>( dat )</a>
<a class="sourceLine" id="cb153-3" title="3">smokersstar &lt;-<span class="st"> </span>shuffle[<span class="dv">1</span><span class="op">:</span>N]</a>
<a class="sourceLine" id="cb153-4" title="4">nonsmokersstar &lt;-<span class="st"> </span>shuffle[(N<span class="op">+</span><span class="dv">1</span>)<span class="op">:</span>(<span class="dv">2</span><span class="op">*</span>N)]</a>
<a class="sourceLine" id="cb153-5" title="5"><span class="kw">mean</span>(smokersstar)<span class="op">-</span><span class="kw">mean</span>(nonsmokersstar)</a></code></pre></div>
<pre><code>## [1] -8.5</code></pre>
<p>The last value is one observation from the null distribution we will construct. Set the
seed at 1, and then repeat the permutation 1,000 times to create a null distribution. What
is the permutation derived p-value for our observation?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" title="1">N &lt;-<span class="st"> </span><span class="dv">10</span></a>
<a class="sourceLine" id="cb155-2" title="2"></a>
<a class="sourceLine" id="cb155-3" title="3"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb155-4" title="4">nonsmokers &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.nonsmoke,N)</a>
<a class="sourceLine" id="cb155-5" title="5">smokers &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.smoke,N)</a>
<a class="sourceLine" id="cb155-6" title="6">obs &lt;-<span class="st"> </span><span class="kw">mean</span>(smokers) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(nonsmokers)</a>
<a class="sourceLine" id="cb155-7" title="7"></a>
<a class="sourceLine" id="cb155-8" title="8"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb155-9" title="9">res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, {</a>
<a class="sourceLine" id="cb155-10" title="10">  dat &lt;-<span class="st"> </span><span class="kw">c</span>(smokers,nonsmokers)</a>
<a class="sourceLine" id="cb155-11" title="11">  shuffle &lt;-<span class="st"> </span><span class="kw">sample</span>(dat)</a>
<a class="sourceLine" id="cb155-12" title="12">  smokersstar &lt;-<span class="st"> </span>shuffle[<span class="dv">1</span><span class="op">:</span>N]</a>
<a class="sourceLine" id="cb155-13" title="13">  nonsmokersstar &lt;-<span class="st"> </span>shuffle[(N<span class="op">+</span><span class="dv">1</span>)<span class="op">:</span>(<span class="dv">2</span><span class="op">*</span>N)]</a>
<a class="sourceLine" id="cb155-14" title="14">  avgdiff &lt;-<span class="st"> </span><span class="kw">mean</span>(smokersstar) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(nonsmokersstar)</a>
<a class="sourceLine" id="cb155-15" title="15">  <span class="kw">return</span>(avgdiff)</a>
<a class="sourceLine" id="cb155-16" title="16">  </a>
<a class="sourceLine" id="cb155-17" title="17">})</a>
<a class="sourceLine" id="cb155-18" title="18"></a>
<a class="sourceLine" id="cb155-19" title="19">(<span class="kw">sum</span>(<span class="kw">abs</span>(res_list) <span class="op">&gt;</span><span class="st"> </span><span class="kw">abs</span>(obs)) <span class="op">+</span><span class="dv">1</span>)<span class="op">/</span>(<span class="kw">length</span>(res_list)<span class="op">+</span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.05294705</code></pre>
<p>Due to the random numbers, the actual answer might differ.</p>
</div>
<div id="question-2-6" class="section level3">
<h3><span class="header-section-number">3.7.2</span> Question 2</h3>
<div class="question">
<p>Repeat the above exercise, but instead of the differences in mean, consider the differences in median <code>obs &lt;- median(smokers) - median(nonsmokers)</code>. What is the permutation based p-value?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" title="1">N &lt;-<span class="st"> </span><span class="dv">10</span></a>
<a class="sourceLine" id="cb157-2" title="2"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb157-3" title="3">nonsmokers &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.nonsmoke,N)</a>
<a class="sourceLine" id="cb157-4" title="4">smokers &lt;-<span class="st"> </span><span class="kw">sample</span>(bwt.smoke,N)</a>
<a class="sourceLine" id="cb157-5" title="5">obs &lt;-<span class="st"> </span><span class="kw">median</span>(smokers) <span class="op">-</span><span class="st"> </span><span class="kw">median</span>(nonsmokers)</a>
<a class="sourceLine" id="cb157-6" title="6"></a>
<a class="sourceLine" id="cb157-7" title="7"><span class="kw">set.seed</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb157-8" title="8">res_list &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, {</a>
<a class="sourceLine" id="cb157-9" title="9">  dat &lt;-<span class="st"> </span><span class="kw">c</span>(smokers,nonsmokers)</a>
<a class="sourceLine" id="cb157-10" title="10">  shuffle &lt;-<span class="st"> </span><span class="kw">sample</span>(dat)</a>
<a class="sourceLine" id="cb157-11" title="11">  smokersstar &lt;-<span class="st"> </span>shuffle[<span class="dv">1</span><span class="op">:</span>N]</a>
<a class="sourceLine" id="cb157-12" title="12">  nonsmokersstar &lt;-<span class="st"> </span>shuffle[(N<span class="op">+</span><span class="dv">1</span>)<span class="op">:</span>(<span class="dv">2</span><span class="op">*</span>N)]</a>
<a class="sourceLine" id="cb157-13" title="13">  avgdiff &lt;-<span class="st"> </span><span class="kw">median</span>(smokersstar) <span class="op">-</span><span class="st"> </span><span class="kw">median</span>(nonsmokersstar)</a>
<a class="sourceLine" id="cb157-14" title="14">  <span class="kw">return</span>(avgdiff)</a>
<a class="sourceLine" id="cb157-15" title="15">  </a>
<a class="sourceLine" id="cb157-16" title="16">})</a>
<a class="sourceLine" id="cb157-17" title="17">(<span class="kw">sum</span>(<span class="kw">abs</span>(res_list) <span class="op">&gt;</span><span class="st"> </span><span class="kw">abs</span>(obs)) <span class="op">+</span><span class="dv">1</span>)<span class="op">/</span>(<span class="kw">length</span>(res_list)<span class="op">+</span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.01798202</code></pre>
<p>Due to the random numbers, the actual answer might differ.</p>
</div>
</div>
<div id="ch-2.25-exercises" class="section level2">
<h2><span class="header-section-number">3.8</span> Ch 2.25 Exercises</h2>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" title="1">d =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;assoctest.csv&#39;</span>)</a></code></pre></div>
<div id="question-1-8" class="section level3">
<h3><span class="header-section-number">3.8.1</span> Question 1</h3>
<div class="question">
<p>This dataframe refects the allele status (either AA/Aa or aa) and the case/control status for 72 individuals. Compute the Chi-square test for the association of genotype with case/control status (using the <code>table</code> function and the <code>chisq.test</code> function). Examine the table to see if it looks enriched for association by eye. What is the X-squared statistic?</p>
</div>
<div class="answer">

<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">table</span>(d)</a>
<a class="sourceLine" id="cb160-2" title="2"><span class="kw">chisq.test</span>(tab)<span class="op">$</span>statistic</a></code></pre></div>
<pre><code>## X-squared 
##  3.343653</code></pre>
</div>
<div id="question-2-7" class="section level3">
<h3><span class="header-section-number">3.8.2</span> Question 2</h3>
<div class="question">
<p>Compute Fisher’s exact test fisher.test for the same table. What is the p-value <strong>(two-tailed)</strong>?</p>
</div>
<div class="answer">


<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" title="1"><span class="kw">fisher.test</span>(tab)<span class="op">$</span>p.value</a></code></pre></div>
<pre><code>## [1] 0.05193834</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="getting-started.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/YOUR GITHUB USERNAME/YOUR REPO NAME/edit/master/inference.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/YOUR GITHUB USERNAME/YOUR REPO NAME/blob/master/inference.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
